### ISSUE TITLE
PUT behaves like PATCH, but it shouldn't

### ISSUE THREAD

**Issue by Thinkscape** [zfcampus/zf-apigility-doctrine#102]
By common understanding, the difference between REST PUT and PATCH is that PUT expects full entity information (all fields) that will be injected in place of all existing fields. PATCH on the other hand only touches fields that are provided in the payload, leaving other values intact.

Currently there is no difference in the way PUT (`update()`) and PATCH (`patch()`) perform updates on an entity.

See also #100

**Comment by adamlundrigan** [comment]
IMO it would be sufficient to rely on the InputFilter to handle that: if the input filter accepts the payload then it's a valid representation of the object.  The trouble is then getting around the issue of not knowing what fields the hydrator expects. The only solution I see is replacing the entity currently persisted with the new one, but i'm not sure if Doctrine ORM supports that (possibliy through `replace`?).

Personally, I'd like to see patch work like described in [RFC 6902](http://tools.ietf.org/html/rfc6902) ([tl;dr version here](http://williamdurand.fr/2014/02/14/please-do-not-patch-like-an-idiot/)), but at this stage that's a pipedream at best (as the default behavior anyway, I know it can be achieved through adding a module)

**Comment by Thinkscape** [comment]
@TomHAnderson It's not zf-apigility-doctrine's responsibility to validate `$data` completeness. It's either input filter or hydrator, both which are user's responsibility. Then, there's default values in the model - many of my models will just assume values if not provided.

In other words, why would the controller care? The worst that can happen is a failed `INSERT` statement, which again, is an effect of invalid data being sent (same as any other underflow). For any extra logic one can write listeners, play with the controller or filter/hydrator.

**Comment by TomHAnderson** [comment]
I don't think there's anything we can do about this.  Closing until someone has a solution.
