### ISSUE TITLE
Type casting of collections and embedded docs

### ISSUE THREAD

**Issue by MassiAtZend** [zfcampus/zf-apigility-doctrine#110]
I am wondering what would be the best approach for being able to query filter by embedded documents field and collections elements.

Right now I have implemented a quick and dirty solution in method 'typeCastField' of ZF\Apigility\Doctrine\Server\Collection\Filter\ODM\AbstractFilter, but I am sure there is a better solution for that.

Best regards,
M.

**Comment by TomHAnderson** [comment]
This is a zf-doctrine-querybuilder question.
Please post an example with your code change to https://github.com/zfcampus/zf-doctrine-querybuilder-filter
