### ISSUE TITLE
skelet app [question]

### ISSUE THREAD

**Issue by kukoman** [zfcampus/zf-apigility-doctrine#119]
hi there;

I've read the documentation and it looks nice, but now i want to try all the things and here the documentation doesn't really helps me as i don't know where to start.
I have working apigility project with few doctrine entities that are working as expected. 
Now, how to use all the goodies from this module, especially filtering?
I expected it to work after including "zfcampus/zf-apigility-doctrine": "dev-master", into my composer.json and I imagined it to work after querying my collection as the following: /equipment?orderBy[id]=DESC
but it doesn't affect the result :(
anyone can help me with required steps to get it all together?
thank you

**Comment by sjwdavies** [comment]
Hi Tom,

Great work with RollnAPi and great to see it's basis now being worked on here.

I'm new to ZF2 and Apigility and am trying to get this Module working with Apigility but the documentation is non-existant to say the least.

Are you able to point us in the direction of a Skeleton App for this module as the RollnAPi seems to have terminated.

Thanks in advance,
Steve

**Comment by TomHAnderson** [comment]
Roll'n API is now two modules:  
https://github.com/TomHAnderson/apigility-oauth2-doctrine-skeleton
https://github.com/TomHAnderson/zf-oauth2-client-test
