### ISSUE TITLE
Doctrine Adapter link does not show in Dashboard

### ISSUE THREAD

**Issue by canetech** [zfcampus/zf-apigility-doctrine#132]
im not sure if it's a bug in the admin UI, but the Doctrine adapter menu is not viewable in Dashboard.
i filed it in the admin-ui page too https://github.com/zfcampus/zf-apigility-admin-ui/issues/5

can i manually view the Doctrine adapter page?

**Comment by jguittard** [comment]
It will be available in Apigility 1.1
