### ISSUE TITLE
Complex Queries Through Routes Parameters

### ISSUE THREAD

**Issue by gabrielsomoza** [zfcampus/zf-apigility-doctrine#136]
In the README.md file you describe the possibility of using complex queries through route parameters.

Just to put this a bit more in context: I have a Person service and a PersonRole service (both with their associated Doctrine Entities). I want to expose the PersonRole service at: `/api/persons/:person_id/roles[/:personrole_id]`

But that's not really working for me.. here's my setup: 

https://gist.github.com/gabrielsomoza/c23dee4482ea17e942a6

1. The only reason it works on the Entitiy is because I'm specifying the PersonRole ID is specified: the Person ID is not really used in the query at all (it seems).
2. But it definitely doesn't work on the Collection endpoint: when queried, it just ignores the `person_id` parameter and simply returns all available PersonRoles in the database.

Looking at `ZF\Apigility\Doctrine\Server\Resource\DoctrineResource::fetchAll` it definitely doesn't look like any of the RouteMatch params are applied to the query builder. There doesn't seem to be any listeners that would do that either.

My inclination right now is to listen to the `DoctrineResourceEvent::EVENT_FETCH_ALL_PRE` event and manually inject the `:person_id` parameter into the Query Builder.

However, other tickets have mentioned it should be possible seemingly out of the box: https://github.com/zfcampus/zf-apigility/issues/10#issuecomment-30845576 - and I can't seem to find the right combination of settings to get it to work. Any ideas? Or should I go for the custom listener approach?

**Comment by TomHAnderson** [comment]
There is a PR with a new README.  https://github.com/zfcampus/zf-doctrine-querybuilder-filter/pull/1
