### ISSUE TITLE
Examples needed

### ISSUE THREAD

**Issue by tartan75** [zfcampus/zf-apigility-doctrine#138]
I'm new to ZF2, apigility and doctrine, and trying to get to grips with the combination. I've been using https://github.com/StukiOrg/RollnApi/ as a very helpful example, but am hitting an error:

   "title": "Internal Server Error",
    "status": 500,
    "detail": "Argument 1 passed to DoctrineModule\\Stdlib\\Hydrator\\DoctrineObject::__construct() must be an instance of Doctrine\\Common\\Persistence\\ObjectManager, null given, called in /var/websites/digtrackusr/vendor/zfcampus/zf-apigility-doctrine/src/Server/Resource/DoctrineResource.php on line 148 and defined"

I suspect that this arises as my doctrine entity uses annotation. I also wonder if I should be creating a DoctrineResourceFactory, but the only example I could find on that links to a deleted repository. Are there any examples of using Apigility with doctrine and an annotated entity?

**Comment by TomHAnderson** [comment]
Don't suspect your annotations but rather is the proper entity manager referenced in the config?

```
    'zf-apigility' => array(
        'doctrine-connected' => array(
            'DbApi\\V1\\Rest\\Artist\\ArtistResource' => array(
                'object_manager' => 'doctrine.entitymanager.orm_default',
                'hydrator' => 'DbApi\\V1\\Rest\\Artist\\ArtistHydrator',
            ),
```

and 

```
    'doctrine-hydrator' => array(
        'DbApi\\V1\\Rest\\Artist\\ArtistHydrator' => array(
            'entity_class' => 'Db\\Entity\\Artist',
            'object_manager' => 'doctrine.entitymanager.orm_default',
            'by_value' => false,
            'strategies' => array(
                'album' => 'ZF\\Apigility\\Doctrine\\Server\\Hydrator\\Strategy\\CollectionExtract',
            ),
            'use_generated_hydrator' => true,
        ),
```

Does Roll'n API work out of the box and just not when you created your entities?  When you replaced the existing xml defined entities did you edit the config for doctrine?

```
    'doctrine' => [
        'driver' => [
            'db_driver' => [
                'class' => 'Doctrine\ORM\Mapping\Driver\XmlDriver',
                'paths' => [__DIR__ . '/xml'],
            ],
           'orm_default' => [
                'class'   => 'Doctrine\ORM\Mapping\Driver\DriverChain',
                'drivers' => [
                    __NAMESPACE__ . '\Entity' => 'db_driver',
                ],
            ],
        ],
    ],
```

**Comment by tartan75** [comment]
Thanks and apologies. re-checking those elements revealed I had missed a change to a module name. Post now works for a sIngle entity. Now to the challenge - trying to trace why get returns an empty object {}.

**Comment by evanb2** [comment]
Under 'doctrine-hydrator' what does the 'by_value' boolean doing? And what is the 'strategies' array doing? I'm having trouble with a POST request and don't understand enough to know how to debug.
