### ISSUE TITLE
Returning ApiProblem from DoctrineResource listener

### ISSUE THREAD

**Issue by leonrodenburg** [zfcampus/zf-apigility-doctrine#140]
It seems that the DoctrineResourceEvents that were implemented for #77 are only useful for modifying collections or entities before they are provided through the endpoint. But what if you'd want to completely prevent access to a resource? This would be useful to prevent users from listing, modifying or deleting resources that they don't have access to. The return value of listeners that attach to DoctrineResource's events is not used when fetching, creating, updating or deleting entities. Wouldn't it be convenient to be able to do this:

```php
$sharedEvents->attach('ZF\Apigility\Doctrine\Server\Resource\DoctrineResource', '*', function ($e) {
    if (/* OAuth2 identity does not have access to this entity or collection */) {
        $e->stopPropagation(true);
        return new ApiProblem(404, 'The resource was not found');
    }
});
```

I see that the `triggerDoctrineEvent()` method returns a ResponseCollection, but the `fetch()`, `create()` etc. do not check for something like an ApiProblem in the responses.

Am I overlooking something?

**Comment by TomHAnderson** [comment]
I think that's a workable idea and worth the time to build.  Will you submit a PR?

**Comment by leonrodenburg** [comment]
Yes, I'll submit it today.
