### ISSUE TITLE
entities posted as a collection insert to database as null

### ISSUE THREAD

**Issue by tartan75** [zfcampus/zf-apigility-doctrine#144]
I'm trying to insert multiple objects in a single post. In my own code I was getting errors on the DB insert: 'null not allowed'. After scouring for any typos. I've then set up the great example I had been refering to: https://github.com/StukiOrg/RollnApi.

get (entity and collection) and post  (for a single entity) works when I've been testing with artist, but while I can post

{
    "name": "testnwr1"
}

If I post:
[{
    "name": "testnwr2"
},
{
    "name": "testnwr3"
}]

I get:
{
    "name": null,
    "id": 102,
    "_embedded": {
        "album": []
    },
    "_links": {
        "self": {
            "href": "http://test.localhost/api/artist/102"
        }
    }
}

The name has gone to null: exactly the error I was getting on my own implimentation.

Am i doing something wrong with the syntax for the data posted? The example on github was configures to allow post of a collection.

Many thanks

Nathan

**Comment by nesinervink** [comment]
+1

**Comment by TomHAnderson** [comment]
https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Resource/DoctrineResource.php#L347
The create method

The patchList method
https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Resource/DoctrineResource.php#L422
You'll notice there is not a createList method.  

The ancestor for the resource:
https://github.com/zfcampus/zf-rest/blob/master/src/AbstractResourceListener.php#L151
Does not have an event for createList

If you want the ability to create list you need to start back here then work your way forward back to here.
