### ISSUE TITLE
UPGRADE files

### ISSUE THREAD

**Issue by veewee** [zfcampus/zf-apigility-doctrine#149]
Hello @TomHAnderson 

Good to see you working on this project again!
I am trying to opgrade from an old version of zf-apigility-doctrine (<0.1.0) to the latest one (0.3.0)
Lots of stuff changed, but there is no documentation available. This is a real pain...

My suggestion: Create an UPGRADE-version-nr.md file per new version.
For now I got following changes (which cover an upgrade from old dev-master to 0.3.0):

# Module changes

- Install and configure zf-doctrine-querybuilder according the documentation
- Make sure to add the use with apigility doctrine part!

# Configuration adjustments

- Add 'entity_identifier_name' key to the zf-rest config. This is the name of the identifier property of your entity.
- Change key 'zf-collection-query' to 'zf-apigility-doctrine-query-provider'
- Change key 'query_provider' in zf-apigility > doctrine-connected to 'query_providers' according to https://github.com/zfcampus/zf-apigility-doctrine#query-providers. Example:

```
'query_providers' => array(
    'default' => 'default_odm',
    'fetch_all' => 'Key.in.zf-apigility-doctrine-query-provider',
),
```

# Class adjustments

- Change interface of query provider classes to: ZF\Apigility\Doctrine\Server\Query\Provider\QueryProviderInterface or extend the DefaultOrm / DefaultOdm. (Note: you could also use the defaults from the querybuilder module)
- Prepend the $resourcEvent to the createQuery and change logic if needed

# Implementation adjustments
- Change the 'query' parameter to 'filters' (in $_GET)
- Change the 'sort' parameter to 'order-by' (in $_GET)

Note:
I am bumping into issue: https://github.com/zfcampus/zf-doctrine-querybuilder/pull/3. This one is blocking.
Are the changes above complete or is there anything else I have to do to get it working again?

Maybe it's a good idea to tag a basic version of the querybuilder module and add those UPGRADE.Md files to make sure upgrading this module is easy as well.

Thanks!

**Comment by TomHAnderson** [comment]
I merged in https://github.com/zfcampus/zf-doctrine-querybuilder/pull/3

Thanks for the docs!  The latest work has really brought this into a more mature state.  When I started the project I didn't have a big picture of what the final product should look like and that's developed recently.

**Comment by veewee** [comment]
Yes it has. That's a good thing!
The only problem is upgrading to this stable version for people who are already using an older version :)

**Comment by TomHAnderson** [comment]
https://github.com/zfcampus/zf-apigility-doctrine/tree/master/docs
