### ISSUE TITLE
BC break

### ISSUE THREAD

**Issue by amdopsworks** [zfcampus/zf-apigility-doctrine#153]
I've update the version of my apigility doctrine module and it broke my system.

I've added the `entity_identifier_name` where needed and it fixed some of my "GET"s, but in one of my REST resource I overridden the findEntity method and I don't call the doctrine resource logic but my own.
However, now this method expects another argument - `$method` - and I don't know what is its purpose.

**Comment by TomHAnderson** [comment]
In the 0.3.0 series Query Providers are introduced.  See the README.md for details about Query Providers.  

The $method passed to findEntity tells the function which Query Provider to use: https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Resource/DoctrineResource.php#L663

You may be interested in this UPGRADE guide:  https://github.com/zfcampus/zf-apigility-doctrine/issues/149
