### ISSUE TITLE
Does DoctrineResource#findEntity use entityIdentifierName?

### ISSUE THREAD

**Issue by kusmierz** [zfcampus/zf-apigility-doctrine#154]
DoctrineResource#findEntity() will always use strictly Entity's identifier (the real one).

```php
$classMetaData = $this->getObjectManager()->getClassMetadata($this->getEntityClass());
$identifierFieldNames = $classMetaData->getIdentifierFieldNames();
```

But what if I'd like to get entity using another field, ie. by an email? Should I override resource's fetch() method to do it?

**Comment by kusmierz** [comment]
What's more, this code: https://github.com/zfcampus/zf-apigility-doctrine/blob/f4380c78eefee74c5e0b291af37495e582c6ffe9/src/Server/Resource/DoctrineResource.php#L639-660 in my mind is useless, as long as identifierField(s) is/are uniq.

**Comment by TomHAnderson** [comment]
I think's it's plum loony.  But that doesn't mean folks don't want to do it.

Because the findEntity function uses a QueryBuilder it does not need to use a primary key:  https://github.com/zfcampus/zf-apigility-doctrine/blob/develop/src/Server/Resource/DoctrineResource.php#L673
so if you tried it I don't see why it wouldn't work but a unit test showing that it doesn't would be a great PR.

**Comment by TomHAnderson** [comment]
Oh, ok, I get what you're saying now.  You think instead of using identifier names we should use the entity_identifier_name as a delimited string for multiple keyed entites?  e.g. "email.storeId" such that for a single field you could entity_identifier_name = email and pass the email as a primary key?  Well, maybe it's only teal bonkers.  

Using the routeMatchParameters[entity_identifier_name] = identifier has merit.  I'll gladly accept a PR if you use the multiKeyDelimiter for both entity_identifier_name and id.

**Comment by kusmierz** [comment]
Dunno if we are talking about the same :)

I'd change it like this:

```php
    protected function findEntity($id, $method)
    {
        $classMetaData = $this->getObjectManager()->getClassMetadata($this->getEntityClass());

        if (!empty($this->getEntityIdentifierName())) {
            $identifierFieldNames = $this->getEntityIdentifierName();

            if (!is_array($identifierFieldNames)) {
                $identifierFieldNames = [$identifierFieldNames];
            }
        } else {
            $identifierFieldNames = $classMetaData->getIdentifierFieldNames();
        }

        $criteria = array();
```

I'll treat `$classMetaData->getIdentifierFieldNames()` as default field name(s), but allow to change it using `entityIdentifierName` property. Otherwise, indeed I could add some criteria using `routeMatchParameters`, but... here https://github.com/zfcampus/zf-apigility-doctrine/blob/develop/src/Server/Resource/DoctrineResource.php#L639 `$criteria` var will have always `$id` value. So if you have your id field uniq, you could only add criteria which return the Entity (ie. with correct email address, etc) or return null (as long as all params are `andWhere`, which should be also changable in my mind). For example:

```php
$criteria = ['id' => $id, 'email' => $routeMatchParam['email']]; // will return $id Entity, as long as email is correct, so we have to know $id as well!
```

Anyway, I've Entity with id and email fields. ID is PK. Try to write config, which allow me to get entity by email (without changing Entity, in particular PK :))

**Comment by TomHAnderson** [comment]
@kusmierz Please take a look at the hotfix linked here.  I include a unittest of an entity with the name as the identifying field and that unittest passes.

**Comment by kusmierz** [comment]
I've added some comments. And yes, I think this is it, thank you!

**Comment by kusmierz** [comment]
Now looks OK, I think you could merge this PR.

Anyway still I don't understand how this loop works exactly (or what is for):
https://github.com/TomHAnderson/zf-apigility-doctrine/blob/hotfix/entity_identifier_name/src/Server/Resource/DoctrineResource.php#L637-654

just by the way:
https://github.com/TomHAnderson/zf-apigility-doctrine/blob/hotfix/entity_identifier_name/src/Server/Resource/DoctrineResource.php#L671
maybe instead will be better something like (quicker, more readable and better while debuging):

```php
$parameterName = uniqid($key);
```

**Comment by TomHAnderson** [comment]
That loop is for routes like /api/resource/<identifier>/subkey/<subkeyidentifier>

Since I've ran db.etree.org for 15 years and etree used md5 files before flac embedded the checksums in the file I like the affinity.
