### ISSUE TITLE
Cannot generate the resources

### ISSUE THREAD

**Issue by wesleywillians** [zfcampus/zf-apigility-doctrine#159]
Hello Folks,

I am trying to use the module, but I got stuck with a error 500.

I am executing: http://localhost:35424/apigility/api/module/WebApi/doctrine/Artist
1) I already created the entity: WebApi\Entity\Artist
2) Setup doctrine in module.config.php in WebApi Module
3) My Post data (using postman)
![screen shot 2015-02-17 at 5 55 40 pm](https://cloud.githubusercontent.com/assets/399218/6236261/2f3505ec-b6d0-11e4-9cc7-2a0128ad8c6b.png)

I got this error:
https://gist.github.com/anonymous/bfe04d87347e9416339b

I could see that some files were created: lile ArtistResource.php

Any help?

**Comment by TomHAnderson** [comment]
You need to post the data as a JSON string.

**Comment by wesleywillians** [comment]
Hello Tom, I already did it, and got other error, saying that I did not provide the ServiceName. I can see that it did not receive my args. 

Have a look:
{
    "trace": [
        {
            "file": "/Users/wesley/Zend/workspaces_tutorials/Apigility-Doctrine/vendor/zfcampus/zf-apigility-doctrine/src/Admin/Model/NewDoctrineServiceEntity.php",
            "line": 41,
            "function": "exchangeArray",
            "class": "ZF\\Apigility\\Admin\\Model\\NewRestServiceEntity",
            "type": "->",
            "args": [
                []
            ]
        },

**Comment by TomHAnderson** [comment]
Please post your JSON request.  Did you specify application/json as the content type?

**Comment by wesleywillians** [comment]
Ops, I had only the Accept.. Forgot the content-type.
Now, I got the same 500 error as before.

{
    "objectManager": "doctrine.entitymanager.orm_default",
    "serviceName": "Artist",
    "entityClass": "WebApi\\Entity\\Artist",
    "routeIdentifierName": "artist_id",
    "entityIdentifierName": "id",
    "routeMatch": "/api/artist"
}
