### ISSUE TITLE
Does not return Nested Entities

### ISSUE THREAD

**Issue by takethefake** [zfcampus/zf-apigility-doctrine#164]
It does not resolve my InnerEntities on which the queried Entity depends on for example /core/app depends on category but category is not resolved? 

```json
{
    "ident": "GROUPINGDEMO",
    "jsClassname": "Ic.view.protocol.ProtocolList",
    "position": 1,
    "active": true,
    "version": "1",
    "css": "icon-numbered-list",
    "id": 1,
    "category": {
        "__initializer__": { },
        "__cloner__": { },
        "__isInitialized__": false
    },
    "_links": {
        "self": {
            "href": "http:\/\/ilmcon\/core\/app\/1"
        }
    }
}
```
i read that i have to assign a hydrator but this was not supported in the current dev-develop apigility-admin-ui because the category field was not created initially. 

how is this working?

**Comment by TomHAnderson** [comment]
Add the referenced entities to the doctrine-connected part of your config.  It's kinda easier to add the referenced entity as an api endpoint then remove the code and route.  Either way, try that.

**Comment by takethefake** [comment]
can you please describe this a little more detailed?
1.if i add the referenced entity into the doctrine-connected part which key should i use?

2. Creating a new Endpoint means creating a doctrine connected resource for core category?
which code should i remove to which route?

Thanks

**Comment by takethefake** [comment]
Is there a possibility to to display bidirectional relations? 
To stick to the example above:
i have a One-to-Many Relationship from CoreCategory to CoreApp 
Also there exists a Function getApps() in Core Category to receive a Collection of apps

can this be achieved?

**Comment by jguittard** [comment]
As mentionned on IRC, you need to handle how you want to populate your entity with its relation(s) at the hydration level. Write your custom hydrator and declare it in your config
