### ISSUE TITLE
Filter by route params in fetchAll

### ISSUE THREAD

**Issue by rodsouto** [zfcampus/zf-apigility-doctrine#165]
Hi, 

if I have two entities (user and map), a request to /api/user/2/map/1 returns the map filtered with user=2, but a request to /api/user/2/map ignores this filter and returns all existing maps

I would expect it to work the same in both cases, wouldn't it be possible to extract the logic from findEntity() and filter by route params in fetchAll? (and probably in all other methods too?)

**Comment by TomHAnderson** [comment]
You can extend your resources to custom classes and write your own findEntity.

Alternatively you could not use multiple keys and instead use the extra key in the Query Provider to create the filter you're looking for.

**Comment by rodsouto** [comment]
Thanks I will try that, but I wonder why route filters works as expected by default with entities (https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Resource/DoctrineResource.php#L666) but not with collections

**Comment by TomHAnderson** [comment]
@rodsouto I'm going to close this for now.  You're the first to bring up collections of subkeys and if you want to experiment you do know the right place in the code to start from.  I'll look forward to any PRs.

**Comment by rodsouto** [comment]
If somebody else is interested, for now i'm using this .https://gist.github.com/rodsouto/2d305d2b3385226587ed. If there's interest in this functionality I'll send a PR later. Thanks!
