### ISSUE TITLE
broken on development

### ISSUE THREAD

**Issue by Perfect-Web** [zfcampus/zf-apigility-doctrine#167]
Call to a member function getClassMetadata() on null in vendor/zfcampus/zf-apigility-doctrine/src/Server/Resource/DoctrineResource.php on line 631

**Comment by TomHAnderson** [comment]
ohh you ment here: https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Resource/DoctrineResource.php#L631

To debug your error validate the object manager for the class is correct.

**Comment by Perfect-Web** [comment]
sorry, was false alarm, it was because of something else
