### ISSUE TITLE
Invalid OAuth2Server instance returned

### ISSUE THREAD

**Issue by guliano** [zfcampus/zf-apigility-doctrine#172]
Due to changes in https://github.com/zfcampus/zf-oauth2/pull/93 factory of `ZF\OAuth2\Service\OAuth2Server` returns `Closure` instead of `OAuth2\Server`. This throws an exception, when the resource is not protected by oAuth.
```
Catchable fatal error: Argument 1 passed to ZF\Apigility\Doctrine\Server\Query\Provider\AbstractQueryProvider::setOAuth2Server() must be an instance of OAuth2\Server, instance of Closure given, called in /home/guliano/work/calendar/vendor/zfcampus/zf-apigility-doctrine/src/Server/Resource/DoctrineResourceFactory.php on line 276 and defined in /home/gully/work/goodyear/calendar/vendor/zfcampus/zf-apigility-doctrine/src/Server/Query/Provider/AbstractQueryProvider.php on line 66
```
This can be fixed by adding `()` to the ```$oAuth2Server``` variable at https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Resource/DoctrineResourceFactory.php#L217 and https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Resource/DoctrineResourceFactory.php#L276

Bug occurs with latest [zf-mvc-auth](https://github.com/zfcampus/zf-mvc-auth/tree/1.1.1) and [zf-oauth2](https://github.com/zfcampus/zf-oauth2/tree/1.1.1) at version `1.1.1`. At `1.1.0` is ok.

**Comment by jensstalder** [comment]
Is this related to?
```
Catchable fatal error: Argument 1 passed to ZF\Apigility\Doctrine\Server\Query\Provider\AbstractQueryProvider::setOAuth2Server() must be an instance of OAuth2\Server, instance of ZF\OAuth2\Factory\OAuth2ServerInstanceFactory given,
```

**Comment by guliano** [comment]
Yes it is, but I see @TomHAnderson just fixed it.

**Comment by jensstalder** [comment]
Well... even at dev-master the exception still appears. This breaks my api.

**Comment by guliano** [comment]
This is fixed in develop branch for now.

**Comment by TomHAnderson** [comment]
I've moved the fix to master: https://github.com/zfcampus/zf-apigility-doctrine/releases/tag/0.4.1

**Comment by pearson-lucas-dev** [comment]
I am getting this error  Call to undefined method Closure::handleTokenRequest()  This is what is leading up to that.
```
This is in the factory and $services is passed into the constructor of the class
$services = $controllers->getServiceLocator()->get('ServiceManager');

This line is in the constructor
$this->server = $services->get('ZF\OAuth2\Service\OAuth2Server');


This line is further down
$response = $this->server->handleTokenRequest(...variable here...);
```
I am not sure if this is related or not but I am on zf-oauth2 - 1.1.2  and zf-mvc-auth 1.1.


Any help will be appreciated!

**Comment by TomHAnderson** [comment]
Since Apigiltity 1.1 a call to $services->get('ZF\OAuth2\Service\OAuth2Server'); returns a closure.  Resolve the closure by calling it's invoke then handle the token request

```
$oauth2Server = $services->get('...');
$this->server = $oauth2Server();
$respose = $this->server->handleTokenRequest...
```

**Comment by pearson-lucas-dev** [comment]
Thanks for the help that fixed it!
