### ISSUE TITLE
Apply criteria in findEntity() based on route params should not be always automatic

### ISSUE THREAD

**Issue by thomasvargiu** [zfcampus/zf-apigility-doctrine#186]
I think it's a bad idea apply automatic criteria based on route params. If someone uses a custom query provide, he expects to use his query builder.
I suggest to add some parameter in ```doctrine-connected``` configuration do disable this feature.
What do you think?

**Comment by TomHAnderson** [comment]
You're suggesting the addition of the :id required by Apigility to access a fetch route be configured to not execute.  So all filtering would be done in a Query Builder.  I see why you'd want to do that but I'll need other supporters of the idea before not using a different abstract for the resources is prefered.

**Comment by thomasvargiu** [comment]
I mean that ```findEntity``` apply automatic criteria. If I remember correctly, it's used by ```RpcController```, but it's not intended to be used for REST resources. This doesn't respect Single Responsibility Principle and it could be confusing for some users (I am the first) because you allow routing params in for single entities but not for collections. We could force the user to use RPC service to do that. Also, the worst problem, the resource could apply criteria the user doesn't expect when mixing route params and query builders
If someone would want to use route params, he could use them in his custom query builder.
I'm suggesting to handle route params criteria somewhere else to be used just in ```RpcController```.
Pros:
- More consistency
- Better clean code
- More testable (for real unit tests)
Cons:
- BC break for who using route params for fetching single entities (needs a minor release)

**Comment by TomHAnderson** [comment]
To provide an elegant interface a collection should not have route parameters.  You can add filters using zfcampus/zf-doctrine-querybuilder or query filters and with those two there's not a need for route parameters on collection end points.

Because of get based query builder filters with zf-doctrine-querybuilder I can't see a reason to need route parameters.  Can you speak to this?  And a PR with your idea would help too.
