### ISSUE TITLE
Fresh Install: Doctrine configuration broken

### ISSUE THREAD

**Issue by sjwdavies** [zfcampus/zf-apigility-doctrine#192]
Guys,

Firstly, this is a great Library and having used ZF1 and Doctrine2 together before, this seems the ideal marriage.

However, after clean installing about 4 times I come up with the same errors and don't seem to be able to get this to work 'out of the box'. Apologies if this is not an issue, and it's 'me being thick', but there's very little documentation so I don't know if this is an error or not?

Basically, when using the Apigility Skeleton App, adding this using Composer, when trying to create a Doctrine Connected REST Service, the following is shown:

> Doctrine configuration broken
> You have not yet configured any Doctrine connection, and thus cannot create a Doctrine-Connected > service.
> 
> Please refer to the documentation page and define validation configuration for your Doctrine connection.

And the link to 'documentation' doesn't work, just sends you back to the UI homescreen.

Cheers,
Steve

**Comment by TomHAnderson** [comment]
Did you create a doctrine configuration in your local.php file?

**Comment by sjwdavies** [comment]
Hi Tom,

No - I've tried on previous installs today but can't seem to get the syntax and Entity Manager definition correct.

It would be great if the documentation was updated to include an example, or even better if one was included in the ./config folder as a template?

Also, should the admin.config.php and server.config.php be copied over to the ./config/autoload folder?

Sorry if these sound like stupid questions, just the documentation's not great and i'm new to Apigility and ZF2 (used ZF1 for years).

Steve

**Comment by TomHAnderson** [comment]
It is out of scope for this Apigility repository to explain how to configure Doctrine.  See the Doctrine documentation in doctrine/doctrine-orm-module or other Doctrine related resources for that.

You may find the README and my skeleton useful: https://github.com/TomHAnderson/apigility-oauth2-doctrine-skeleton

**Comment by sjwdavies** [comment]
Thanks Tom... I understand.

As an 'issue' though, if anything, the UI could be updated to remove the link to documentation that doesn't work.

Keep up the good work - it's appreciated.

Steve

**Comment by TomHAnderson** [comment]
Please send a PR with corrections to invalid documentation.

**Comment by sjwdavies** [comment]
Tom - just to confirm - does this Library 'bridge the gap' to allow Apigility to talk to Doctrine?

Should I also have the doctrine/doctrine-orm-module installed?

Steve

**Comment by TomHAnderson** [comment]
This module supports ORM and ODM.  I refer you to the skeleton for ORM and the unit tests for ODM.

**Comment by santiph** [comment]
@sjwdavies This are the steps I've followed:
After a clean Apigility instalation, I've added this modules on the application.config.php file:
```
        'Phpro\\DoctrineHydrationModule',
        'ZF\\Apigility\\Doctrine\\Server',
```
and this one on development.config.php:
```
        'ZF\\Apigility\\Doctrine\\Admin',
```


After that, all you need is to create a file called "doctrine.local.php" under your autoload folder with this content modified to fit your needs to configure Doctrine:

```
<?php
return array(
    'doctrine' => array(
        'connection' => array(
            'orm_default' => array(
                'driverClass' => 'Doctrine\DBAL\Driver\PDOMySql\Driver',
                'params' => array(
                    'charset' => 'utf8',
                    'host' => 'localhost',
                    'port' => '3306',
                    'user' => 'user',
                    'password' => 'password',
                    'dbname' => 'dbname',
                )
            )
        )
    ),
);

```

I'm still trying to figure how and where the entities should be created and properly configured to follow the Zf2/Apigility architecture and folder distributions. I'll keep you posted once I've figured this out. ;)

PS: @TomHAnderson I really really REALLY think you should consider adding "Phpro\\DoctrineHydrationModule" module to the instructions on your README file. It's hard to start figuring this things out for new users like myself based only on the error stack.

**Comment by jguittard** [comment]
@sjwdavies regarding the entity configuration, it's just a matter of telling Doctrine where are located your entities. As for ZF2 architecture, assuming you have numerous modules, add the following to each and every module that contains Doctrine entities:
```php
<?php
return [
...
'doctrine' => [
        'driver' => [
            'account_driver' => [
                'class' => '\Doctrine\ORM\Mapping\Driver\AnnotationDriver',
                'cache' => 'array',
                'paths' => [
                    __DIR__ . '/../src/Account/Entity',
                ],
            ],
            'orm_default' => [
                'drivers' => [
                    'Account\Entity' => 'account_driver',
                ],
            ],
        ],
    ],
...
]
```
This way you have the liberty to define different annotation engines per module, and maybe have a different path pattern for each one of them.

Lastly, about the Doctrine Hydration Module, I will discuss updating the README with @TomHAnderson.
I also have several improvements to implement to the UI I built. Should you have other suggestions, please address them to the [Admin UI repository](https://github.com/zfcampus/zf-apigility-admin-ui).
Thanks.

**Comment by mrnod** [comment]
I have to agree with @sjwdavies - the documentation is dreadful, in fact so bad you might as well not bother maintaining it.

**Comment by TomHAnderson** [comment]
@mrnod It would certainly be helpful to have an independent documentation author who can describe the use of the code without the author.  The source speaks for itself.  Pull requests, including for documentation, is welcome.
