### ISSUE TITLE
Service Manager removed from DoctrineResource

### ISSUE THREAD

**Issue by Tomdarkness** [zfcampus/zf-apigility-doctrine#199]
We have a very small number of instances where we need to completely replace the behaviour of one of the methods in a DoctrineResource which requires use of some other classes registered in the ZF2 service manager.

Ideally we'd like to inject the dependancies but this has never been possible because of how the DoctrineResource classes are instantiated (by a simple new $className in the factory). However, we had been working around this by taking advantage of the fact that the service manager is actually injected into the resource meaning we can access the SM from within the resource.

This is obviously not a good great solution but we absolutely require this completely custom behaviour for a specific method but would like to keep the normal DoctrineResource behaviour for the rest of the methods.

But the SM is no longer injected as of 0e49889573e8f5631b956da1849b3fda861859ad which just has a commit message of "unit test improvements". 

@TomHAnderson would be great if you could clarify why this was removed. Would be even better if we could get it added back in.

Alternatively perhaps a better solution would be to create a optional configuration parameter that would allow you to specific that the resource should be fetched from the service manager in the DoctrineResourceFactory.

**Comment by weierophinney** [comment]
Fixed with #202, and to be released in v1.0.3 next week.
