### ISSUE TITLE
Unable to determine entity identifier for object of type "XXX"; no fields matching "id"

### ISSUE THREAD

**Issue by starchild2** [zfcampus/zf-apigility-doctrine#204]
Hello, I'm struggling with zf-apigility-doctrine module.
I created an entity with Doctrine and created the respective MySQL db.
Then I activated the zf-apigility-doctrine module, logged in the admin page, created a new api, then a new service, then I selected "doctrine connected" then I selected my previously created doctrine entity the I pushed save.
But when I go to the url (ex. http://myserver/api/tasks/1) I receive the following error:

Unable to determine entity identifier for object of type "XXX"; no fields matching "id"

The entity I creted HAS a "id" field and its the identifier. In fact if I go in the apigility panel and check the "fields" of my task entity I note that all the fields are there minus the "id" field.

How can I resolve that problem? Please help

**Comment by jguittard** [comment]
Did you add Doctrine Hydration module in your project ?

Julien.

**Comment by starchild2** [comment]
Yes, this is my application.config.php

return array(
    'modules' => array(
        'ZendDeveloperTools',
        'DoctrineModule',
        'DoctrineORMModule',
        'Application',
        'ZF\\DevelopmentMode',
        'ZF\\Apigility',
        'Phpro\\DoctrineHydrationModule',
        'ZF\\Apigility\\Doctrine\\Server',
        'ZF\\Apigility\\Provider',
        'ZF\\Apigility\\Documentation',
        'AssetManager',
        'ZF\\ApiProblem',
        'ZF\\Configuration',
        'ZF\\OAuth2',
        'ZF\\MvcAuth',
        'ZF\\Hal',
        'ZF\\ContentNegotiation',
        'ZF\\ContentValidation',
        'ZF\\Rest',
        'ZF\\Rpc',
        'ZF\\Versioning',
        'KirinDB',
        'KirinUI',
        'testapi',
        'KirinAPI',
    ),

**Comment by jguittard** [comment]
Does the FQCN of the entity class defined in your service in the admin UI match the FQCN of your Doctrine entity?

Julien.

**Comment by starchild2** [comment]
I've done everything with the admin gui, not touched the code by hand at all.
Could you please tell me how could I check the FQCNs?

**Comment by jguittard** [comment]
In the Admin UI, locate your service on the left navigation pane, and display its information. At the bottom left of the « General settings » first tab, you’ll see a field called « Entity Class ». It contains the FQCN (Fully Qualified Class Name = namespace + class name). That may be the one generated by Apigility. It has to match the FQCN of YOUR Doctrine entity.
So you may need to update this field and save.

Julien.

**Comment by starchild2** [comment]
I checked and confirm that FQCN is correct:

Entity class on admin ui: MyDB\Entity\User

this is the actual entity file:
<?php
namespace MyDB\Entity;
use Doctrine\ORM\Mapping as ORM;
/** @ORM\Entity */
class User {
        /**
         * @ORM\Id
         * @ORM\GeneratedValue(strategy="AUTO")
         * @ORM\Column(type="integer")
         */
        protected $id;

        /** @ORM\Column(type="string") */
        protected $fullname;

        public function setFullname($fullname) {
                $this->fullname = $fullname;
        }

        public function getFullname() {
                return $this->fullname;
        }
}

**Comment by jguittard** [comment]
Do you have a match in your ['zf-hal’][‘metadata-map’] for this entity ?
Also in its hydrator entry ?

**Comment by starchild2** [comment]
I'm a beginner so please explain me where should I go to check...
I used the admin ui and nothing else...

**Comment by starchild2** [comment]
If I understand well this is what you're asking:

    'zf-hal' => array(
        'metadata_map' => array(
            'MyDB\\Entity\\User' => array(
                'route_identifier_name' => 'user_id',
                'entity_identifier_name' => 'id',
                'route_name' => 'kirin-api.rest.doctrine.user',
                'hydrator' => 'KirinAPI\\V1\\Rest\\User\\UserHydrator',
            ),
            'MyAPI\\V1\\Rest\\User\\UserCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'my-api.rest.doctrine.user',
                'is_collection' => true,
            ),
        ),
    ),

**Comment by jguittard** [comment]
Correct,

Now do you find the entry « KirinAPI\\V1\\Rest\\User\\UserHydrator »  in doctrine-hydrator in this same config file ? And a match in [zf-apigility][‘doctrine-connected’]['KirinAPI\\V1\\Rest\\User\\UserResource’] ?
And did you define accessors for your $id field in your entity ? User::getId() and User::setId($id) ?

**Comment by starchild2** [comment]
I'm sending the entire module.config:


<?php
return array(
    'router' => array(
        'routes' => array(
            'kirin-api.rest.doctrine.task' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/task[/:task_id]',
                    'defaults' => array(
                        'controller' => 'KirinAPI\\V1\\Rest\\Task\\Controller',
                    ),
                ),
            ),
            'kirin-api.rest.doctrine.user' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/api/user[/:user_id]',
                    'defaults' => array(
                        'controller' => 'KirinAPI\\V1\\Rest\\User\\Controller',
                    ),
                ),
            ),
        ),
    ),
    'zf-versioning' => array(
        'uri' => array(
            0 => 'kirin-api.rest.doctrine.task',
            1 => 'kirin-api.rest.doctrine.user',
        ),
    ),
    'zf-rest' => array(
        'KirinAPI\\V1\\Rest\\Task\\Controller' => array(
            'listener' => 'KirinAPI\\V1\\Rest\\Task\\TaskResource',
            'route_name' => 'kirin-api.rest.doctrine.task',
            'route_identifier_name' => 'task_id',
            'entity_identifier_name' => 'id',
            'collection_name' => 'task',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'KirinDB\\Entity\\Task',
            'collection_class' => 'KirinAPI\\V1\\Rest\\Task\\TaskCollection',
            'service_name' => 'Task',
        ),
        'KirinAPI\\V1\\Rest\\User\\Controller' => array(
            'listener' => 'KirinAPI\\V1\\Rest\\User\\UserResource',
            'route_name' => 'kirin-api.rest.doctrine.user',
            'route_identifier_name' => 'user_id',
            'entity_identifier_name' => 'id',
            'collection_name' => 'user',
            'entity_http_methods' => array(
                0 => 'GET',
                1 => 'PATCH',
                2 => 'PUT',
                3 => 'DELETE',
            ),
            'collection_http_methods' => array(
                0 => 'GET',
                1 => 'POST',
            ),
            'collection_query_whitelist' => array(),
            'page_size' => 25,
            'page_size_param' => null,
            'entity_class' => 'KirinDB\\Entity\\User',
            'collection_class' => 'KirinAPI\\V1\\Rest\\User\\UserCollection',
            'service_name' => 'User',
        ),
    ),
    'zf-content-negotiation' => array(
        'controllers' => array(
            'KirinAPI\\V1\\Rest\\Task\\Controller' => 'HalJson',
            'KirinAPI\\V1\\Rest\\User\\Controller' => 'HalJson',
        ),
        'accept-whitelist' => array(
            'KirinAPI\\V1\\Rest\\Task\\Controller' => array(
                0 => 'application/vnd.kirin-api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
            'KirinAPI\\V1\\Rest\\User\\Controller' => array(
                0 => 'application/vnd.kirin-api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
        ),
        'content-type-whitelist' => array(
            'KirinAPI\\V1\\Rest\\Task\\Controller' => array(
                0 => 'application/json',
            ),
            'KirinAPI\\V1\\Rest\\User\\Controller' => array(
                0 => 'application/json',
            ),
        ),
        'accept_whitelist' => array(
            'KirinAPI\\V1\\Rest\\Task\\Controller' => array(
                0 => 'application/json',
                1 => 'application/*+json',
            ),
        ),
        'content_type_whitelist' => array(
            'KirinAPI\\V1\\Rest\\Task\\Controller' => array(
                0 => 'application/json',
            ),
        ),
    ),
    'zf-hal' => array(
        'metadata_map' => array(
            'KirinDB\\Entity\\Task' => array(
                'route_identifier_name' => 'task_id',
                'entity_identifier_name' => 'id',
                'route_name' => 'kirin-api.rest.doctrine.task',
                'hydrator' => 'KirinAPI\\V1\\Rest\\Task\\TaskHydrator',
            ),
            'KirinAPI\\V1\\Rest\\Task\\TaskCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'kirin-api.rest.doctrine.task',
                'is_collection' => true,
            ),
            'KirinDB\\Entity\\User' => array(
                'route_identifier_name' => 'user_id',
                'entity_identifier_name' => 'id',
                'route_name' => 'kirin-api.rest.doctrine.user',
                'hydrator' => 'KirinAPI\\V1\\Rest\\User\\UserHydrator',
            ),
            'KirinAPI\\V1\\Rest\\User\\UserCollection' => array(
                'entity_identifier_name' => 'id',
                'route_name' => 'kirin-api.rest.doctrine.user',
                'is_collection' => true,
            ),
        ),
    ),
    'zf-apigility' => array(
        'doctrine-connected' => array(
            'KirinAPI\\V1\\Rest\\Task\\TaskResource' => array(
                'object_manager' => 'doctrine.entitymanager.orm_default',
                'hydrator' => 'KirinAPI\\V1\\Rest\\Task\\TaskHydrator',
            ),
            'KirinAPI\\V1\\Rest\\User\\UserResource' => array(
                'object_manager' => 'doctrine.entitymanager.orm_default',
                'hydrator' => 'KirinAPI\\V1\\Rest\\User\\UserHydrator',
            ),
        ),
    ),
    'doctrine-hydrator' => array(
        'KirinAPI\\V1\\Rest\\Task\\TaskHydrator' => array(
            'entity_class' => 'KirinDB\\Entity\\Task',
            'object_manager' => 'doctrine.entitymanager.orm_default',
            'by_value' => true,
            'strategies' => array(),
            'use_generated_hydrator' => true,
        ),
        'KirinAPI\\V1\\Rest\\User\\UserHydrator' => array(
            'entity_class' => 'KirinDB\\Entity\\User',
            'object_manager' => 'doctrine.entitymanager.orm_default',
            'by_value' => true,
            'strategies' => array(),
            'use_generated_hydrator' => true,
        ),
    ),
    'zf-content-validation' => array(
        'KirinAPI\\V1\\Rest\\Task\\Controller' => array(
            'input_filter' => 'KirinAPI\\V1\\Rest\\Task\\Validator',
        ),
        'KirinAPI\\V1\\Rest\\User\\Controller' => array(
            'input_filter' => 'KirinAPI\\V1\\Rest\\User\\Validator',
        ),
    ),
    'input_filter_specs' => array(
        'KirinAPI\\V1\\Rest\\Task\\Validator' => array(
            0 => array(
                'name' => 'author',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\Digits',
                    ),
                ),
                'validators' => array(),
            ),
            1 => array(
                'name' => 'lastEditor',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\Digits',
                    ),
                ),
                'validators' => array(),
            ),
            2 => array(
                'name' => 'created',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            3 => array(
                'name' => 'modified',
                'required' => true,
                'filters' => array(),
                'validators' => array(),
            ),
            4 => array(
                'name' => 'deleted',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\Digits',
                    ),
                ),
                'validators' => array(),
            ),
            5 => array(
                'name' => 'series',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            6 => array(
                'name' => 'taskNumber',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            7 => array(
                'name' => 'taskTypology',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            8 => array(
                'name' => 'taskStatus',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            9 => array(
                'name' => 'taskStartDate',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            10 => array(
                'name' => 'taskDueDate',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            11 => array(
                'name' => 'taskEndDate',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            12 => array(
                'name' => 'taskCustomer',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            13 => array(
                'name' => 'taskContractCustomer',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            14 => array(
                'name' => 'gasSpot',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            15 => array(
                'name' => 'tankSerialNumber',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            16 => array(
                'name' => 'requestText',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            17 => array(
                'name' => 'notes',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            18 => array(
                'name' => 'technician',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            19 => array(
                'name' => 'dateSet',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            20 => array(
                'name' => 'attachments',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            21 => array(
                'name' => 'operatorSign',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
            22 => array(
                'name' => 'customerInvoice',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
        ),
        'KirinAPI\\V1\\Rest\\User\\Validator' => array(
            0 => array(
                'name' => 'fullname',
                'required' => true,
                'filters' => array(
                    0 => array(
                        'name' => 'Zend\\Filter\\StringTrim',
                    ),
                    1 => array(
                        'name' => 'Zend\\Filter\\StripTags',
                    ),
                ),
                'validators' => array(),
            ),
        ),
    ),
    'zf-mvc-auth' => array(
        'authorization' => array(
            'KirinAPI\\V1\\Rest\\Task\\Controller' => array(
                'collection' => array(
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ),
                'entity' => array(
                    'GET' => false,
                    'POST' => false,
                    'PUT' => false,
                    'PATCH' => false,
                    'DELETE' => false,
                ),
            ),
        ),
    ),
);



p.s. No, I have not declared getId() and setId($id) in my Entity. should I?

**Comment by jguittard** [comment]
For the config file, a « Yes » would have had been enough :)
And yes, you should and you must. Quick explanation:
DoctrineHydrationModule relies on Doctrine's own implementation of the ClassMethods hydrator. Meaning that it extracts data from your entity through the getters, and hydrates through setters.
More information about hydrators: http://framework.zend.com/manual/current/en/modules/zend.stdlib.hydrator.html.

When Doctrine retrieves your entity data, and build an object from your entity class with this data, it will call every setter mapping your properties.

Ex:
```php
<?php

namespace Account\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * Class User
 *
 * @package Account\Entity
 *
 * @ORM\Entity
 * @ORM\Table(name="user")
 */
class User
{
    /**
     * Primary identifier
     *
     * @var int
     * @ORM\Id
     * @ORM\Column(type="integer", options={"unsigned"=true})
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    /**
     * User's first name
     *
     * @var string
     * @ORM\Column(name="first_name", type="string", length=255, nullable=false)
     */
    protected $firstName;

    /**
     * User's last name
     *
     * @var string
     * @ORM\Column(name="last_name", type="string", length=255, nullable=false)
     */
    protected $lastName;

    /**
     * Get the primary identifier
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }
    /**
     * Set the primary identifier
     *
     * @param int $id
     * @return EntityTrait
     */
    public function setId($id)
    {
        $this->id = $id;
        return $this;
    }

    /**
     * Get user's first name
     *
     * @return string
     */
    public function getFirstName()
    {
        return $this->firstName;
    }
    
    /**
     * Set user's first name
     *
     * @param string $firstName
     * @return User
     */
    public function setFirstName($firstName)
    {
        $this->firstName = $firstName;
        return $this;
    }

    /**
     * Get user's last name
     *
     * @return string
     */
    public function getLastName()
    {
        return $this->lastName;
    }

    /**
     * Set user's last name
     *
     * @param string $lastName
     * @return User
     */
    public function setLastName($lastName)
    {
        $this->lastName = $lastName;
        return $this;
    }
}
```
What happened in your case is that zf-hal expected an _id_ field to be provided so that it can generate appropriate links but couldn't.

Julien.

**Comment by starchild2** [comment]
Got it! Thank you.
It was that I did not declare the getter and setters for the id field. Thank you so much for your explanation, very appreciated!
