### ISSUE TITLE
ArrayCollection always empty on "One-To-Many" side of the relationship

### ISSUE THREAD

**Issue by starchild2** [zfcampus/zf-apigility-doctrine#205]
Hello, me again.
Working with zf-apigility-doctrine and two entities: Task.php and TaskDetail.php.

TaskDetail is child of Task and a Task can have multiple TaskDetails (Master/Detail concept).

This is my code:

=============================================================
<pre><code>
<?php

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity
 * @ORM\Table(name="tasks")
 */
class Task extends BaseEntity {
	// ID FIELD IS DEFINED IN BaseEntity
	
	/**
	 * @ORM\OneToMany(targetEntity="\KirinDB\Entity\TaskDetail", mappedBy="task", cascade={"persist"})
	 * */
	private $details;

	// This is the constructor. It initializes all aspects of the entity
	public function __construct() {
		$this->details = new ArrayCollection();
	}

	//
	//	GETTERS AND SETTERS
	//
	public function getDetails() {
		return $this->details;
	}

	public function setDetails($details) {

		// set the task field on the detail to be sure the foreign_key on the
		// TaskDetail objects is set when the Task object is persisted.
		foreach ($details as $detail) {
			$detail->setTask($this);
		}

		$this->details = $details;
	}
}

=============================================================

<?php

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="taskdetails")
 */
class TaskDetail extends BaseEntity {
	// ID FIELD IS DEFINED IN BaseEntity
	/**
	 * @ORM\ManyToOne(targetEntity="\KirinDB\Entity\Task", inversedBy="details")
	 **/
	private $task;

	//
	//	GETTERS AND SETTERS
	//
	public function getTask() {
		return $this->task;
	}

	public function setTask($task) {
		$this->task = $task;
	}
}
</pre></code>
=============================================================

Then I proceed and create a service for Task with zf-apigility-doctrine admin ui but when I test the service if i get a taskdetail (calling /api/task-detail/1) in the json I have the parent "Task" entity inside the "_embedded" property. If I get a Task (calling /api/task/1) in the json I have a property called "details" but it is empty.

What am I doing wrong? Please help, thank you so much

**Comment by TomHAnderson** [comment]
Use a he drat or strategy if you want to return inverse relationships.  And
use max_deprh to avoid recurrsion.

**Comment by starchild2** [comment]
I was thinking about that, fact is I don't see the column "tasks" on the Admin UI... how can I add a hydrator strategy (what strategy is needed? Is there anything predefined to use?)?
Could you please dig into details? I'm a beginner and today I struggled with it so much...

Thank you!

**Comment by santiph** [comment]
@starchild2 under the module.config.php file of your module, you'll find a section for doctrine-hydrator.
In there, a collection of hydrator configurations for each serviced entity you've created will be found.
On the strategies array, you need to add a key/value pair indicating the attribute of the entity you want to hydrate, and the hydrator class you wish to use for it.
For example:

```
            'strategies' => array(
                'details' => 'ZF\\Apigility\\Doctrine\\Server\\Hydrator\\Strategy\\CollectionExtract',
            ),
```

Btw, @TomHAnderson what happened with the CollectionLink hydrator? It's not present on ZF\\Apigility\\Doctrine\\Server\\Hydrator\\Strategy\\ namespace any more.

**Comment by PowerKiKi** [comment]
@santiph this was extremely useful information. I spent a lot of time trying to achieve that. I still have a few question though:

I seem to get the exact same result by configuring ``zf-hal``, instead of ``doctrine-hydrator``, the following way:
```php
<?php

return array(
    // ... other config
    'zf-hal' => array(
        'metadata_map' => array(
            'Doctrine\ORM\PersistentCollection' => array(
                'hydrator' => 'ArraySerializable',
                'isCollection' => true,
            ),
            // ... other config
        ),
    ),
);
```

Would you be able to explain what is the difference and which alternatives would be considered best practices ?

Also why is it not the behavior out of the box ? I would think that it is something that most people would like to implement. But maybe there are good reasons not to make it out of the box ? What downsides could there be ?

**Comment by evanb2** [comment]
How are we supposed to know what all of these settings are? Where is the documentation for all of this? Am I missing something?

**Comment by TomHAnderson** [comment]
@evanb2 if there is something missing from the README.md contributions are welcome.  You may find my blog useful: http://blog.tomhanderson.com and if you still require help you may find it at https://apiskeletons.com
