### ISSUE TITLE
Ensure module works on HHVM

### ISSUE THREAD

**Issue by weierophinney** [zfcampus/zf-apigility-doctrine#207]
#206 updated the QA toolchain, and finally setup the tests so that they run on PHP 7 and HHVM. Tests are passing on PHP 7, but all but one test on HHVM either errors or fails:
- https://travis-ci.org/zfcampus/zf-apigility-doctrine/jobs/70284347

It looks like these are likely due to differences in how `json_decode()` works, but they need to be addressed.

**Comment by TomHAnderson** [comment]
Needing to pass PHP7 is expected but is passing HHVM now a requirement of zfcampus?

**Comment by weierophinney** [comment]
@TomHAnderson Passing HHVM is a nice-to-have, and considering that every other module passes, this module then is an outlier.

In both the case of PHP 7 and HHVM, *not* passing does not invalidate a build, and we can ship without them passing. But I'd like to track them as much as possible to ensure the widest compatibility.

**Comment by webimpress** [comment]
We are not going to support HHVM anymore.
For more information please see: https://framework.zend.com/blog/2017-06-06-zf-php-7-1.html
