### ISSUE TITLE
Unrecognized identifier fields

### ISSUE THREAD

**Issue by starchild2** [zfcampus/zf-apigility-doctrine#208]
Hello,
I have a apigility-doctrine API and I'm trying to post this json:
<pre>
{
    "requestNumber": 7,
    "details":[
     {
          "rowNumber":0
      }
     ]
}
</pre>

If I POST this with chrome postman I receive an error message saying:
"The identifier id is missing for a query of KirinDB\Entity\TaskDetail".

If I POST that json:
<pre>
{
    "id":1,
    "requestNumber": 7,
    "details":[
     {
          "id":1,
          "rowNumber":0
      }
     ]
}
</pre>

Then I receive this message:
Unrecognized identifier fields: 'rowNumber' are not present on class 'KirinDB\\\\Entity\\\\TaskDetail

The classes are Task and TaskDetail.
Task has a field named "details" which is OneToMany mapped to TaskDetail and TaskDetail is mapped ManyToOne to Task.

Please help, I'm struggling with this thing...

**Comment by starchild2** [comment]
This is the trace:


<pre>
{
  "trace": [
    {
      "file": "/var/www/kirin-web/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php",
      "line": 403,
      "function": "missingIdentifierField",
      "class": "Doctrine\\\\ORM\\\\ORMException",
      "type": "::",
      "args": [
        "KirinDB\\\\Entity\\\\TaskDetail",
        "id"
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/doctrine/doctrine-module/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php",
      "line": 493,
      "function": "find",
      "class": "Doctrine\\\\ORM\\\\EntityManager",
      "type": "->",
      "args": [
        "KirinDB\\\\Entity\\\\TaskDetail",
        {
          "rowNumber": 0
        }
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/doctrine/doctrine-module/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php",
      "line": 421,
      "function": "find",
      "class": "DoctrineModule\\\\Stdlib\\\\Hydrator\\\\DoctrineObject",
      "type": "->",
      "args": [
        {
          "rowNumber": 0
        },
        "KirinDB\\\\Entity\\\\TaskDetail"
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/doctrine/doctrine-module/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php",
      "line": 276,
      "function": "toMany",
      "class": "DoctrineModule\\\\Stdlib\\\\Hydrator\\\\DoctrineObject",
      "type": "->",
      "args": [
        {},
        "details",
        "KirinDB\\\\Entity\\\\TaskDetail",
        [
          {
            "rowNumber": 0
          }
        ]
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/doctrine/doctrine-module/src/DoctrineModule/Stdlib/Hydrator/DoctrineObject.php",
      "line": 106,
      "function": "hydrateByValue",
      "class": "DoctrineModule\\\\Stdlib\\\\Hydrator\\\\DoctrineObject",
      "type": "->",
      "args": [
        {
          "requestNumber": 7,
          "details": [
            {
              "rowNumber": 0
            }
          ]
        },
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/phpro/zf-doctrine-hydration-module/src/Hydrator/DoctrineHydrator.php",
      "line": 79,
      "function": "hydrate",
      "class": "DoctrineModule\\\\Stdlib\\\\Hydrator\\\\DoctrineObject",
      "type": "->",
      "args": [
        {
          "requestNumber": 7,
          "details": [
            {
              "rowNumber": 0
            }
          ]
        },
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zfcampus/zf-apigility-doctrine/src/Server/Resource/DoctrineResource.php",
      "line": 340,
      "function": "hydrate",
      "class": "Phpro\\\\DoctrineHydrationModule\\\\Hydrator\\\\DoctrineHydrator",
      "type": "->",
      "args": [
        {
          "requestNumber": 7,
          "details": [
            {
              "rowNumber": 0
            }
          ]
        },
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zfcampus/zf-rest/src/AbstractResourceListener.php",
      "line": 157,
      "function": "create",
      "class": "ZF\\\\Apigility\\\\Doctrine\\\\Server\\\\Resource\\\\DoctrineResource",
      "type": "->",
      "args": [
        {
          "requestNumber": 7,
          "details": [
            {
              "rowNumber": 0
            }
          ]
        }
      ]
    },
    {
      "function": "dispatch",
      "class": "ZF\\\\Rest\\\\AbstractResourceListener",
      "type": "->",
      "args": [
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php",
      "line": 444,
      "function": "call_user_func",
      "args": [
        [
          {},
          "dispatch"
        ],
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php",
      "line": 205,
      "function": "triggerListeners",
      "class": "Zend\\\\EventManager\\\\EventManager",
      "type": "->",
      "args": [
        "create",
        {},
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zfcampus/zf-rest/src/Resource.php",
      "line": 246,
      "function": "trigger",
      "class": "Zend\\\\EventManager\\\\EventManager",
      "type": "->",
      "args": [
        {},
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zfcampus/zf-rest/src/RestController.php",
      "line": 369,
      "function": "create",
      "class": "ZF\\\\Rest\\\\Resource",
      "type": "->",
      "args": [
        {
          "requestNumber": 7,
          "details": [
            {
              "rowNumber": 0
            }
          ]
        }
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zfcampus/zf-rest/src/RestController.php",
      "line": 906,
      "function": "create",
      "class": "ZF\\\\Rest\\\\RestController",
      "type": "->",
      "args": [
        {
          "requestNumber": 7,
          "details": [
            {
              "rowNumber": 0
            }
          ]
        }
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractRestfulController.php",
      "line": 416,
      "function": "processPostData",
      "class": "ZF\\\\Rest\\\\RestController",
      "type": "->",
      "args": [
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zfcampus/zf-rest/src/RestController.php",
      "line": 332,
      "function": "onDispatch",
      "class": "Zend\\\\Mvc\\\\Controller\\\\AbstractRestfulController",
      "type": "->",
      "args": [
        {}
      ]
    },
    {
      "function": "onDispatch",
      "class": "ZF\\\\Rest\\\\RestController",
      "type": "->",
      "args": [
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php",
      "line": 444,
      "function": "call_user_func",
      "args": [
        [
          {},
          "onDispatch"
        ],
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php",
      "line": 205,
      "function": "triggerListeners",
      "class": "Zend\\\\EventManager\\\\EventManager",
      "type": "->",
      "args": [
        "dispatch",
        {},
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractController.php",
      "line": 118,
      "function": "trigger",
      "class": "Zend\\\\EventManager\\\\EventManager",
      "type": "->",
      "args": [
        "dispatch",
        {},
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zendframework/zendframework/library/Zend/Mvc/Controller/AbstractRestfulController.php",
      "line": 300,
      "function": "dispatch",
      "class": "Zend\\\\Mvc\\\\Controller\\\\AbstractController",
      "type": "->",
      "args": [
        {},
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zendframework/zendframework/library/Zend/Mvc/DispatchListener.php",
      "line": 93,
      "function": "dispatch",
      "class": "Zend\\\\Mvc\\\\Controller\\\\AbstractRestfulController",
      "type": "->",
      "args": [
        {},
        {}
      ]
    },
    {
      "function": "onDispatch",
      "class": "Zend\\\\Mvc\\\\DispatchListener",
      "type": "->",
      "args": [
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php",
      "line": 444,
      "function": "call_user_func",
      "args": [
        [
          {},
          "onDispatch"
        ],
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zendframework/zendframework/library/Zend/EventManager/EventManager.php",
      "line": 205,
      "function": "triggerListeners",
      "class": "Zend\\\\EventManager\\\\EventManager",
      "type": "->",
      "args": [
        "dispatch",
        {},
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/vendor/zendframework/zendframework/library/Zend/Mvc/Application.php",
      "line": 314,
      "function": "trigger",
      "class": "Zend\\\\EventManager\\\\EventManager",
      "type": "->",
      "args": [
        "dispatch",
        {},
        {}
      ]
    },
    {
      "file": "/var/www/kirin-web/public/index.php",
      "line": 51,
      "function": "run",
      "class": "Zend\\\\Mvc\\\\Application",
      "type": "->",
      "args": []
    }
  ],
  "type": "http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html",
  "title": "Internal Server Error",
  "status": 500,
  "detail": "The identifier id is missing for a query of KirinDB\\\\Entity\\\\TaskDetail"
}
</pre>

**Comment by fabiopaiva** [comment]
Me too

if i pass only the id it work.

    {
        "requestNumber": 7,
        "details":[1,2]
     }

**Comment by TomHAnderson** [comment]
See https://github.com/zfcampus/zf-apigility-doctrine/pull/184
