### ISSUE TITLE
many2many relations

### ISSUE THREAD

**Issue by wimkumpen** [zfcampus/zf-apigility-doctrine#21]
Hey,

In my product I get this link to get my categories. (1 product can have multiple categories, 1 category can have multiple products):

links: {
  categories: {
     href: "http://localhost/api/category?query[0][field]=products&query[0][type]=eq&query[0][value]=1"
  }-
}

When I execute the link it will generate a query like this:

SELECT row FROM Entity\Category row WHERE row.products = 1;

this doesn't work... I'm not an expert in doctrine, but this query should work:
SELECT row FROM Entity\Category row JOIN row.products p WHERE p.id = 1;

No the question is: am I doing something wrong, or is this just nog working in zf-apigility-doctrine?

Second question, the other way around, getting a category with the links to the products is not working because you have just one mappedBy side. Is there a way to solve this?

**Comment by TomHAnderson** [comment]
Closed due to aging.
