### ISSUE TITLE
some dependencies stopped being installed via composer

### ISSUE THREAD

**Issue by akomm** [zfcampus/zf-apigility-doctrine#219]
Hello,

having the following barely changed composer config of apigility skeleton:
https://gist.github.com/akomm/a636e8b596c64c719e7c#file-composer-json-L34
(zfcampus/zf-apigility-doctrine added to require)

I get all the sudden this result:
https://www.dropbox.com/s/v7psbwuhp3y11sb/vendor.png?dl=0
(among others, modules like doctrine/doctrine-orm-module, doctrine/orm, doctrine/dbal are missing)

Although zfcampus/zf-apigility-doctrine has it as dev-dependency:
https://github.com/zfcampus/zf-apigility-doctrine/blob/master/composer.json#L26

I'v installed via composer including require-dev (default)

Brutaly tried following, after softer solutions did not help:
- I'v tried to clear all composer cache and reinstall all deps (including dev)
- I'v deleted the .lock-file, the vendor dir and reinstalled all deps (including dev)

I can add doctrine-orm-module manually, but it kind of smells, since I wlil have to manage the version myself, instead of letting it manage the dependency (zf-apigility-doctrine).

Not even sure if it is composer or zf-apigility-doctrine issue. What can this module possibly do, that composer does not resolve the dependency? So rather a composer problem?

Yesterday it worked. Today after an composer update the pacakges were removed for no obvious reason. Afterward even a clean init of the skeleton and adding the module again does not help. Can't think of any changes I could have done, which broke it.

Composer is up-to-date.
Work since ages with composer and naver experienced something like that.

I still think I'm just stupid or blind and miss something out...

**Comment by TomHAnderson** [comment]
zf-apigility-doctrine supports both orm and odm so the doctrine-orm-module is not included because you might need the odm instead.

See https://github.com/zfcampus/zf-apigility-doctrine/blob/master/composer.json

**Comment by akomm** [comment]
I'v noticed there are two different modules, for different dbs adapters. But in such a case usualy the dep is in suggestion, not require-dev.

**Comment by TomHAnderson** [comment]
https://github.com/zfcampus/zf-apigility-doctrine/pull/235
