### ISSUE TITLE
Proposal: option to filter a collection from route params out of the box

### ISSUE THREAD

**Issue by akomm** [zfcampus/zf-apigility-doctrine#220]
Assume you have the following resources:

- ArticleCollection, URL: __/article__
- ArticleEntity, URL: __/article/:art-id__
- ArticleCommentCollection, URL: __/article/:art-id/comments__
- ArticleCommentEntity, URL: __/article/:art-id/comments/:c-id__

ArticleCommentEntity has a many-to-one association to ArticleEntity via field __article__.

To get a subset of comments for a certain article you have to make some adjustments. Either override in the corresponding ResourceListener or changes in the collection class, or query provider, ... (not all ways listened here).

It would be more convenient if you could simply make a mapping in the config. Map a route param value to be used for query a certain field. In our example: __art-id__ => __article__. The first being the route param name for retrieving a value and the second the field to query against.

This could equaly work for all methods, including create. Currently I have to create create-query-filter each time I want to implement something like that, to inject the association field+value into the comment I want to create (post) out of the route param.

**Comment by TomHAnderson** [comment]
This has been requested before.  I think it will fit best in it's own repository as an extension to this repository.  If you build this as an extension and need changes to this repo to support those changes, such as extending the Resource, submit them here as a PR.
