### ISSUE TITLE
Spelling error in exception class

### ISSUE THREAD

**Issue by akomm** [zfcampus/zf-apigility-doctrine#222]
InvalidArgumentEx**cp**etion should be `InvalidArgumentExcepetion`.

See: [ZF\Apigility\Doctrine\Server\Exception\InvalidArgumentException](https://github.com/zfcampus/zf-apigility-doctrine/blob/0e49889573e8f5631b956da1849b3fda861859ad/src/Server/Exception/InvalidArgumentException.php)

I would fix it but currently tests are broken (#224). I can also make a combined fix PR for everything, if you don't want separate fix PRs.

**Comment by TomHAnderson** [comment]
Fixed in https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Exception/InvalidArgumentException.php
