### ISSUE TITLE
CRUD tests failing do to missing "accept"-headers

### ISSUE THREAD

**Issue by akomm** [zfcampus/zf-apigility-doctrine#223]
Some CRUD tests fail, because - I assume - the test code is not in sync with the code tested.

In `ZFTest\Apigility\Doctrine\Server\ORM\CRUD`

**Test fetch() with listener that returns ApiProblem** fails:
```php
$this->assertEquals(400, $this->getResponseStatusCode());
```
Status actually returned is `406`

Similar issue in other tests.

Reason: content-negotiation kick in before the listener (subject of the test) and produce a 406.
Solution: set the accept header for the test to something like `application/json`.

**Comment by TomHAnderson** [comment]
See #224
