### ISSUE TITLE
Creating doctrine-connected services fail on slow machines

### ISSUE THREAD

**Issue by akomm** [zfcampus/zf-apigility-doctrine#228]
`zf-configuration` uses write locks. Multiple `xhr` cause write failure, when they are not completed fast enough. At least those, executed async and not chained to be executed in ordner. 

This happens always on slower machines (VM environment for example) if you want to create multiple services. Seldom with a single service.

Also some related requests, like creating service and then creating input-filter (subsequent, but dependend calls) should only continue, if previous did not return an problem indicating status. Otherwise it is useless to continue.

**Comment by TomHAnderson** [comment]
I don't read a question into your slow machine problem.  If your developers need a faster machine for 2015 then I support getting one.  

Input filters arn't a part of how Apigility handles Doctrine.  It's a function of the https://github.com/zfcampus/zf-apigility-admin-ui

**Comment by akomm** [comment]
`I don't read a question into your slow machine problem. If your developers need a faster machine for 2015 then I support getting one.`

This isn't getting anyone, anywhere. No reason to be derogatory. If the success of an operation depends on time needed - and we speak here about 1,5-3 seconds for a single doctrine-connected service - it is a problem of the implementation and not the machine. Obviously. 

I'm pretty sure 8 cores @ 4ghz and 8gb ram should be enoguh as host for a vm allowed to use a good portion of the hardware? Its an almost clean vagrant machine provided by `zf-apigility-skeleton`, but the skeleton app is not what matters here, since this is apigility-doctrine. Just to avoid another stuffy replies regarding faster machines.

**Comment by intellix** [comment]
So this is to do with the admin side of Doctrine API calls. Doctrine is pretty heavy and adds a lot of overhead for sure with no caching enabled, I guess this could be an issue?

Is it still a problem with something like proxy generation turned off?

```php
<?php return array(
    'doctrine' => array(
        'configuration' => array(
            'orm_default' => array(
                'metadata_cache' => 'array',
                'query_cache' => 'array',
                'result_cache' => 'array',
                'hydration_cache' => 'array',
                'generate_proxies' => false,
            ),
        ),
    ),
)
```

I suppose being slow is a Doctrine thing but failing to write because of it isn't so good and maybe needs a mention in the `zf-configuration` project.

**Comment by akomm** [comment]
I tend to disable proxy generation even in development by default. So its off and it does not help. I even tried to enable opcache to speed up. It is not enough. I think the performance problem is somehow related with the machine provided by apigility skeleton (puphpet setup), because I have huge stalls on each request. So I think the cause for performance problem in this case is not apigility-doctrine itself. 

So I handle the performance issue separate as not related to this. But it made me notice the issue caused by slow processing.
