### ISSUE TITLE
Update to zend-hydrator

### ISSUE THREAD

**Issue by TomHAnderson** [zfcampus/zf-apigility-doctrine#234]
The hydrator has been removed from zend-stdlib and the namespace has changed.

This module must be updated to use the new namespace as well as it's dependent https://github.com/phpro/zf-doctrine-hydration-module

**Comment by veewee** [comment]
Hi @TomHAnderson,

Long time no see!

I haven't worked on apigility-doctrine for a while now.
Can you give me a heads-up on this new hydrator package?

Is it going to be used in the ZF 2.X series or will it be forced in 3.X ? 
How is Apigility going to introduce this new package?
What about backwards compatibility? It probably needs to be tagged under a new major version with some documentation about how to use it with older versions of ZF / apigility?
At first sight the classes look more or less the same. I wonder if I could just remove `Stdlib` in the source.

Lot's of questions for the moment. I am also available on IRC if you want to talk about it.

Thanks!

**Comment by TomHAnderson** [comment]
Hey Toon, am I going to see you at Zendcon?

The zend-hydrator is a copy over from stdlib and new features have been added very recently but the interfaces are the same.  It's part of ZF 2.5 I believe.

For zf-apigility-doctrine using zend-hydrator should/could be as simple as changing all the namespaces and requiring the package.  

This is only a month old so (now that I backed out a bad release) it's not a pressing priority but should be done in the short term.

**Comment by veewee** [comment]
Sadly I won't be going to Zendcon. Even though I would love to see Vegas, traveling is a bit too expensive / time consuming for the moment.

About the hydrators: 
Since ZF 2.4 is the LTS version, it might be a better idea to stay as compatible with this version?
Otherwise lots of projects wont be able to upgrade to the latest version of doctrine-hydrators.

What is your vision about this?

**Comment by veewee** [comment]
@TomHAnderson 
Any updates on the hydrators?
This is breaking some stuff in the hydration module.

**Comment by TomHAnderson** [comment]
It's time to move on this then?  OK.  This will be a BC break.  I'll put a PR up this week.

**Comment by veewee** [comment]
I don't know it's time to move on. 2.4 is still LTS untill 2018-03-31: http://framework.zend.com/long-term-support/
We also don't get any feedback on the reported issue: https://github.com/zendframework/zend-stdlib/issues/34

**Comment by PowerKiKi** [comment]
My very selfish opinion on that is I don't mind if BC breaks. I plan to upgrade my project when this get solved. But I understand this may not be the case for everyone...

All of that reminds me that I heard about an Apigility 2 in the works (based on middleware), but can't find anything about that on https://github.com/zfcampus. Should it be taken into account when deciding on what to do for hydrators ?

**Comment by TomHAnderson** [comment]
Nobody has said peep to me about Apigility 2.  And it should not be taken into account.  Program for what is here today.  If you program for tomorrow it's like you're committing empty functions into the repo "just in case".

**Comment by PowerKiKi** [comment]
Fair enough. I wasn't sure if you were also working on Apigility 2 or not. I agree with you though that it's best to focus on what we actually have.

**Comment by TomHAnderson** [comment]
I'm going to release a full version update with support for zend-hydrator.  I think projects should stay current through releases and not lag behind simply to stay with a specific version.

**Comment by TomHAnderson** [comment]
I removed the existing commits from master which started the move to zend-hydrator so I could create a new release.  This release allows resource specific hydrators of doctrine resources.

**Comment by stavarengo** [comment]
Hey Guys. Any updates on this issue?

**Comment by TomHAnderson** [comment]
@stavarengo  Currently trying to push this through DoctrineModule in two places:

https://github.com/doctrine/DoctrineModule/pull/548
https://github.com/doctrine/DoctrineModule/pull/558

Please post on those threads, especially the second one, if you can add to the conversation.

**Comment by stavarengo** [comment]
Ok. Thanks @TomHAnderson

**Comment by thomasvargiu** [comment]
@TomHAnderson Any update on this?
I think that the refactoring to make this library compatible with ZF3 will be a bit long, so we could release a version using `Zend\Hydrator`. What do you think?

**Comment by webimpress** [comment]
@thomasvargiu I'm working on it, will be ready soon. We need still tagged doctrine compatibility changes, hopefully it will happen next week.

**Comment by PowerKiKi** [comment]
I lost the "big picture" vision on this.

@webimpress would you be able to list what is left to do to move to zend-hydrator and/or ZF3 ? Are we talking days, weeks or months before a release ?

**Comment by webimpress** [comment]
@PowerKiKi ZF3 compatibility is blocked by doctrine modules, there are still some issues, and we have to wait for stable release. It takes long than I've expected...

**Comment by webimpress** [comment]
Resolved in #267 and released in [2.1.0](https://github.com/zfcampus/zf-apigility-doctrine/releases/tag/2.1.0)
