### ISSUE TITLE
Handling Embeddables

### ISSUE THREAD

**Issue by Lansoweb** [zfcampus/zf-apigility-doctrine#237]
As in http://doctrine-orm.readthedocs.org/projects/doctrine-orm/en/latest/tutorials/embeddables.html, we can have Value Objects mapped as Embedded, but they are not showing in the GET (entity or collection), using by_value = true in the hydrator. 

If i configure the default hydrator with by_value = false, i get an error 
```
Property address.street does not exist
```

What's the best way to handle it? Use a self-made hydrator or should the lib handle it?

Thanks and great work!

**Comment by veewee** [comment]
This should be handled by this library.
I guess that you can attach a new hydrator strategy too the address property.
Which will have following extration result:

```php
[
    'somenormalproperty' => 'value',
    'address' => [
        'street' => 'street'
    ]
]
```

(Note: The extraction should be based on the doctrine metadata of the address value object)

When hydrating, the result from above should be placed in the embedded value object. The value object then needs to be placed in the address property.

**Comment by Lansoweb** [comment]
@veewee Thanks! Will try this solution.
