### ISSUE TITLE
Autodiscovery could not find any existing entities

### ISSUE THREAD

**Issue by IlsonNobrega** [zfcampus/zf-apigility-doctrine#238]
Every time I try to create a service Doctrine-connected it returns this message, I lost a few hours trying in every way to make the tables were brought for me to choose a table to automatically generate the API.
If I create the Zend DB service usually everything works perfectly.

![image](https://cloud.githubusercontent.com/assets/7192737/11346676/e5c95988-9204-11e5-883e-2b56d40a511a.png)

**Comment by TomHAnderson** [comment]
And your application was configured so from a controller you could use the service locator to get() doctrine.entitymanager.orm_default ?

**Comment by inobrega** [comment]
Yes, I tried to connect using the entity manager directly and he connected. Look:

![image](https://cloud.githubusercontent.com/assets/7192737/11347199/7ce82b1c-9207-11e5-93fa-2e9bd580827e.png)

![image](https://cloud.githubusercontent.com/assets/7192737/11347218/8f095d3e-9207-11e5-93da-471a0128be00.png)

I might have forgotten to configure something?

**Comment by IlsonNobrega** [comment]
I understand what's going on. It was my mistake even imagined by this screen I could generate the entities automatically.
But from what I saw I would have to generate them through the terminal and just select them later on Apigility Admin.

![image](https://cloud.githubusercontent.com/assets/7192737/11347608/64837d54-9209-11e5-9616-ab9c725f7000.png)


Sorry for my bad english and for all the inconvenience.

Thanks!

**Comment by jguittard** [comment]
Yes, you’re right. The way I built it was to expose existing entities, meaning DB Connected parses your DB, whereas Doctrine Connected parses your entities definitions.
Sorry on my end for the lack of documentation. Working on it :)

Julien.

**Comment by ilson-nobrega** [comment]
Thanks for listening, documentation is nicely explanatory. Congratulations! But what do you think of a future implementation working exactly like the Db Connected? With the differential to generate the entites automatically...

Ilson Nóbrega

**Comment by TomHAnderson** [comment]
Entities are not database tables and the idea of generating entities from Apigility is not something which will ever occur.  I refer you to https://skipper18.com to ease the creation of your entity defintions.
