### ISSUE TITLE
Collections without paginator

### ISSUE THREAD

**Issue by Wilt** [zfcampus/zf-apigility-doctrine#239]
For `fetchAll` the DoctrineResource does by [default return a paginator](https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Resource/DoctrineResource.php#L559). Is there also a possibility to return a collection without a paginator? Would there be interest in a pull-request to make this possible?

We have some smaller collections for which adding a paginator is totally overkill.

Or is the only way setting page size to -1.

**Comment by TomHAnderson** [comment]
Have you tried creating a Query Provider and returning something which looks like a paginator but isn't?  https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Query/Provider/AbstractQueryProvider.php#L57

If setting the size to -1 works then that would work for me.  If you really feel not using a paginator by not creating your own Query Provider is a better way I'll be sure to look at a PR.

**Comment by TomHAnderson** [comment]
@Wilt anything to add or can I close this?

**Comment by Wilt** [comment]
Our focus moved on other things. We are no longer working on implementing `zf-apigility-doctrine`. I can get back on this later. You can leave open or close (I can request reopening when needed later) whatever you prefer. Thanks!
