### ISSUE TITLE
Deprecation Warning for ServiceLocatorAwareInterface

### ISSUE THREAD

**Issue by JuEger** [zfcampus/zf-apigility-doctrine#245]
As mentioned in zfcampus/zf-apigility-admin#332 ServiceLocatorAwareInterface is deprecated and will be removed in ZF3. 
ZF\Apigility\Doctrine\Admin\Model\DoctrineAutodiscoveryModel extends AbstractAutodiscoveryModel which implements ServiceLocatorAwareInterface.
The ServiceManager is used by DoctrineAutodiscoveryModel and therefore we need to inject it in the factory.
 - [ ] Add ServiceManager as constructor set field (TestCase attributeEquals)
 - [ ] Inject ServiceManager in factory

**Comment by nachaos** [comment]
Will this get fixed soon? Also, is this project under regular maintenance?

**Comment by JuEger** [comment]
Sadly I do not have time to fix this issue myself. I hope someone else has more spare time to fix it. Since it's only a depreciation warning a fix is imho not that important.

**Comment by TomHAnderson** [comment]
Moved to https://github.com/zfcampus/zf-apigility-doctrine/issues/255
