### ISSUE TITLE
POST request json object format

### ISSUE THREAD

**Issue by evanb2** [zfcampus/zf-apigility-doctrine#246]
I'm trying to create a new entity using a POST request, is this the correct format? I'm using Postman to test, and in my response I get a 200 status and it returns the entire collection but doesn't create a new entity.

<img width="603" alt="screen shot 2016-03-04 at 10 09 29 am" src="https://cloud.githubusercontent.com/assets/11276439/13535826/3dad607c-e1f1-11e5-9e0b-36f477e22ae4.png">

**Comment by evanb2** [comment]
Looks like it was an issue with Postman. When I hit the endpoint using httpie it worked.

`http --verify=no POST https://mysite.com/api/v1/practices Content-Type:application/json "{"name":"Blah"}"
`

**Comment by evanb2** [comment]
Another error I made was leaving off the "https://" in Postman.

**Comment by TomHAnderson** [comment]
You know, if you setup the admin correctly with zf-apigility-doctrine admin you can create these resources from with the UI.

**Comment by evanb2** [comment]
Yeah but I just wanted to test that the API was working.
