### ISSUE TITLE
order GET response for resource

### ISSUE THREAD

**Issue by evanb2** [zfcampus/zf-apigility-doctrine#250]
I'm trying to order my GET response for '/users' by last name. I was able to do it by overwriting the default fetchAll() on the User resource. But when I do that I lose all of the built-in pagination and relationship management functionality. Is there are a better way to do this? Maybe through Events?

**Comment by TomHAnderson** [comment]
This repository was created just for external order by and filtering:
https://github.com/API-Skeletons/zf-doctrine-querybuilder
