### ISSUE TITLE
CollectionTotal should be optional

### ISSUE THREAD

**Issue by wshafer** [zfcampus/zf-apigility-doctrine#251]
Hey Guys,

After creating a Custom Query Provider which filters by user_id I noticed that CollectionTotal is coming back.    After reading the PR zfcampus/zf-apigility-doctrine/7 I see two Use Cases that make sense.  But in my use case, I really don't want to broadcast the total number of records in the table to all users.  Is there a way to turn it off?

Thanks,
Westin

**Comment by TomHAnderson** [comment]
It was removed here: https://github.com/zfcampus/zf-apigility-doctrine/commit/e7257639e26817024a0a8e330a83e7d52654440f#diff-d4cefc3db44c1f6ae2ae24fad7055fc8

**Comment by wshafer** [comment]
Thanks.  And wow, great response time!

I did find a way to change the count for the time being.

Thanks again, and special thanks for all the hard work on this module.

**Comment by TomHAnderson** [comment]
If you like zf-apigility-doctrine be sure to check out https://github.com/API-Skeletons
