### ISSUE TITLE
How to inject dependencies into a query create filter?

### ISSUE THREAD

**Issue by clemf** [zfcampus/zf-apigility-doctrine#252]
Hi,
I've been trying to set up a create filter on my resource, but I want to be able to inject my authorization service into the filter so that I can filter based on the logged-in user.

I added the filter to my configuration here:
```
    'zf-apigility' => [
        'doctrine-connected' => [
            'MyApi\\V1\\Rest\\Order\\OrderResource' => [
                'query_create_filter' => 'MyApi\V1\Rest\Order\OrderFilter',
            ],
        ],
    ],
```

And I extended AbstractCreateFilter:
```
use ZF\Apigility\Doctrine\Server\Query\CreateFilter\AbstractCreateFilter;
use ZF\Rest\ResourceEvent;

class OrderFilter extends AbstractCreateFilter
{
    /**
     * @param string $entityClass
     * @param array  $data
     *
     * @return array
     */
    public function filter(ResourceEvent $event, $entityClass, $data)
    {
        // do stuff
        return $data;
    }
}
```

This appears to work, but I can't figure out how to inject my authorization service. Normally I would create a factory, but I don't know how to do that in this instance.

**Comment by TomHAnderson** [comment]
In order to add a filter you must create the filter in the service manager.
https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Module.php#L59-64

```
'zf-apigility-doctrine-query-create-filter' => array(
    'invokables' => array(
        'entity_name' => 'Application\Query\CreateFilter\EntityName',
    )
),
```

That configuration is a plugin manager so you can attach factories, abstract factories, etc. to it.

**Comment by clemf** [comment]
Can you give me an example of how to attach an abstract factory? I've made one like this:

```
class AbstractFilterFactory implements AbstractFactoryInterface
{
    public function canCreateServiceWithName(
        ServiceLocatorInterface $serviceLocator, $name, $requestedName
    ) {
        return (fnmatch('*Filter', $requestedName)) ? true : false;
    }

    public function createServiceWithName(
        ServiceLocatorInterface $serviceLocator,
        $name,
        $requestedName
    ) {
        if (class_exists($requestedName)) {
            $filter = new $requestedName();
            $authService = $serviceLocator->get('Zend\Authentication\AuthenticationService');
            $filter->setAuthService($authService);
            return $filter;
        }

        return false;
    }
}
```
The problem is, I can't figure out the proper configuration to get ZF2 to actually use my factory with the filter class I created.

**Comment by TomHAnderson** [comment]
A Service Manager question is outside the scope of this repo.  Know you're using a plugin manager which is an instance of a Service Manager and you can read up on ZF2's Service Manager and configuration here:  http://framework.zend.com/manual/current/en/modules/zend.service-manager.quick-start.html

**Comment by clemf** [comment]
I appreciate that this may be out of the scope of this repo, and I also appreciate your quick responses. However, I have read through the Service Manager documentation multiple times, and am still having a hard time. Perhaps you can let me know if I am on the right track?

If I am registering the filter as an invokable here: 
```
'zf-apigility-doctrine-query-create-filter' => [
    'invokables' => [
        'Application\Entity\Order\Order' => 'MyApi\V1\Rest\Order\OrderFilter'
    ],
],
```
That means it will not look for any abstract factories, right? However, if I remove that config key and instead add an abstract factory like this:
```
'abstract_factories' => [
    'AudiologyEdgeApi\V1\Rest\AbstractFilterFactory',
],
```
I get a this error when testing it:
```
An abstract factory could not create an instance of myapiv1restordercontroller(alias: MyApi\V1\Rest\Order\Controller).
```
