### ISSUE TITLE
Reference to CollectionLink not removed

### ISSUE THREAD

**Issue by baptistemanson** [zfcampus/zf-apigility-doctrine#253]
https://github.com/zfcampus/zf-apigility-doctrine/blob/fa00dbe016a31754e18d9d13d2c0baf966a21e38/src/Admin/Model/DoctrineRestServiceModel.php#L773

One can see a reference to: ZF\Apigility\Doctrine\Server\Hydrator\Strategy\CollectionLink
This component has been since moved to the queryBuilder if I'm not mistaken.
Is this function used by anyone? We are using our custom scripts for generating the config file.

Thanks!

**Comment by TomHAnderson** [comment]
Moved to https://github.com/API-Skeletons/zf-doctrine-hydrator

**Comment by TomHAnderson** [comment]
I don't think the code generating code is *not* working because of this reference.  That is, this needs to be corrected.
