### ISSUE TITLE
Load different hydrator filters based on query strings?

### ISSUE THREAD

**Issue by clemf** [zfcampus/zf-apigility-doctrine#254]
Hi,

Is it possible to conditionally load hydrator filters? I'm currently using one to filter out fields returned in a user entity. For instance, maybe a query string like `api/users?shallow=true` would dynamically set a filter that returns a shallower field set.

I tried adding a filter within my doctrine resource like this:

```
<?php
namespace TestApi\V1\Rest\Test;

use Application\Entity\Test;
use WebDriver\Exception;
use Zend\Stdlib\Hydrator\Filter\FilterComposite;
use ZF\Apigility\Doctrine\Server\Resource\DoctrineResource;

class TestResource extends DoctrineResource
{
    public function fetchAll($data = [])
    {
        $filter = new TestHydratorFilter();
        $this->getHydrator()->getExtractService()->addFilter(
            "patientList",
            $filter,
            FilterComposite::CONDITION_AND
        );
        parent::fetchAll($data);
    }
}
```

However, this doesn't work as it causes a fatal error in the DoctrineResource `fetchAll()` method:

`Fatal error: Call to a member function setItemCountPerPage() on array in /vendor/zfcampus/zf-apigility-doctrine/src/Server/Resource/DoctrineResource.php on line 582`

Is there a work-around for this or am I going about this the wrong way?

**Comment by TomHAnderson** [comment]
Since https://github.com/zfcampus/zf-apigility-doctrine/releases/tag/2.0.1-beta you can specify different hydrators for each route.  

```php
    'zf-rest' => array(
        'DbApi\\V1\\Rest\\Artist\\Controller' => array(
            'listener' => 'DbApi\\V1\\Rest\\Artist\\ArtistResource',
            ...
            'entity_class' => 'Db\\Entity\\Artist',
            ...
```

This listener then defines it's own hydrator:
```php
    'zf-apigility' => array(
        'doctrine-connected' => array(
            'DbApi\\V1\\Rest\\Artist\\ArtistResource' => array(
                'object_manager' => 'doctrine.entitymanager.orm_default',
                'hydrator' => 'DbApi\\V1\\Rest\\Artist\\ArtistHydrator',
            ),
```

So the hydrator for the resource, not the hydrator for the entity, will be used to hydrate it for that resource.  

The hydrator for an entity looks like this:
```php
    'zf-hal' => array(
        'metadata_map' => array(
            'Db\\Entity\\Artist' => array(
                'route_identifier_name' => 'artist_id',
                'entity_identifier_name' => 'id',
                'route_name' => 'db-api.rest.doctrine.artist',
                'hydrator' => 'DbApi\\V1\\Rest\\Artist\\ArtistHydrator',
            ),
```

**Comment by clemf** [comment]
Hi Tom, thanks for your response. Injecting the request is exactly what I'd like to do. I'm uncertain how to accomplish that. I assume that `RequestAwareTrait` provides the `getRequest` method. Is it possible to give an example of that file?
