### ISSUE TITLE
ZF MVC 3.0.0 compatibility

### ISSUE THREAD

**Issue by TomHAnderson** [zfcampus/zf-apigility-doctrine#255]
@AGmakonts when you get to this repository with your MVC 3.0 changes (thanks, btw!) we can't move this forward because of this problem: https://github.com/doctrine/DoctrineModule/pull/558#issuecomment-207212246

I now think it's filed under the wrong issue but the problem remains.  Until DoctrineModule can implement the changes @weierophinney made when he split zend-hydrator this repository can't follow the rest of the herd.

**Comment by AGmakonts** [comment]
@TomHAnderson thanks for the heads up, I'll be watching this issue.

**Comment by TomHAnderson** [comment]
@AGmakonts Would you be willing to evaluate my PR to fix this?
https://github.com/zfcampus/zf-apigility-doctrine/pull/260

The problem listed above was solved with https://github.com/API-Skeletons/zf-doctrine-module-zend-hydrator
