### ISSUE TITLE
Question: HalJson vs Json

### ISSUE THREAD

**Issue by 4orever** [zfcampus/zf-apigility-doctrine#256]
There was the similar question about empty results with Json content-negotiation: #126 
Please, explain this situation. 

- How should we use Json negotion in a right way?

-  Is there any standard solution without implementing JsonSerializable for each Entity?
- Why HalJson works fine and uses hydrator->extract()?

**Comment by TomHAnderson** [comment]
Are  you asking in the context of a Doctrine Resource or a RPC?  You should never modify the resources generated by this module.  The exceptions are rare.

If you change the configuration of zf-content-negotiation for the controller you want to use Json with it will use the content negotiation you specify.

**Comment by 4orever** [comment]
With this config:
`
    'zf-content-negotiation' => [
        'controllers' => [
            'Catalog\\V1\\Rest\\Product\\Controller' => 'HalJson'
        ]
]
`

when I call `GET /api/product/1`, I got HalJson with all needed data.

But with:
`  'Catalog\\V1\\Rest\\Product\\Controller' => 'Json'`

...I got empty JSON. As you answered in #126 I have to implement JsonSerializable for Doctrine Entity and it works well. But why with **HalJson** I have to do nothing for working? And is there any such 'magic' solution for **Json** too?

**Comment by TomHAnderson** [comment]
zf-apigility-doctrine is intended for HalJson.
You need to use a regular code connected resource if you don't want what this module provides.
