### ISSUE TITLE
The AbstractAutodiscoveryModel must be composed with a service locator

### ISSUE THREAD

**Issue by matwright** [zfcampus/zf-apigility-doctrine#261]
I am currently testing this module, however an exception is being thrown when selecting the document manage in the UI - The AbstractAutodiscoveryModel must be composed with a service locator.

This is thrown because the DoctrineAutodiscoveryModel is instantiated within a factory, yet the service locator is never set hence as soon as the fetchFields method is called the exception is thrown.

The AbstractAutodiscoveryModel from zf-apigility-admin states:

```php
/**
 * This class is instantiated with a $config in some implementations (DbAutodiscoveryModel)
 * but this is dependent on the root service locator for the moduleHasService call below
 * and that must be injected into any class extending this abstract.
 */
```

Hence it would seem logical to set this from within the factory declaration in the Module.php :

```php
$model= new Model\DoctrineAutodiscoveryModel($config);
                    $model->setServiceLocator($services);
                    return $model;
```

instead of 

```php
return new Model\DoctrineAutodiscoveryModel($config);
```

https://github.com/matwright/zf-apigility-doctrine/commit/a08d8368da8f850e0447f467d1b2d0211a4eb179

Happy to provide a unit test and PR

**Comment by TomHAnderson** [comment]
This has been fixed in the pending pull request #260 

I would appreciate your review of this PR!  Will you run your tests again with this PR?

Tom

**Comment by matwright** [comment]
I see this has since been merged into Master, I'll revert back to this version and test, although at a glance I can see that the specific issue I was reporting here has now been remedied. Seem to be quite a few other fixes/updates so will test today.

**Comment by matwright** [comment]
Actually this issue doesn't seem to be addresses, the class is still being instantiated and returned from the factory without setting the service locator:

https://github.com/zfcampus/zf-apigility-doctrine/pull/260/files#diff-6a901958603df1749e0e021d82b922b1R77

**Comment by TomHAnderson** [comment]
https://github.com/zfcampus/zf-apigility-doctrine/pull/262
