### ISSUE TITLE
zf-apigility-admin-ui problem

### ISSUE THREAD

**Issue by gulijiyag** [zfcampus/zf-apigility-doctrine#264]
I installed apigility by the documentation and after that I tried to install zf-apigility-doctrine and I got this error:

> The requested package zfcampus/zf-apigility-admin-ui (locked at 1.2.2, required as ^1.2.3) is satisfiable by zfcampus/zf-apigility-admin-ui[1.2.2] but these conflict with your requirements or minimum-stability.

How to solve this?

**Comment by karborator** [comment]
Same problem here ...

**Comment by webimpress** [comment]
Please try update to the current version. All should be fine. I'd suggest to use `zf-apigility-skeleton 1.4.1` with `zf-apigility-doctrine 2.1.0`. Reopen the issue if you have any further problems. Thanks!
