### ISSUE TITLE
Is there any tutorial?

### ISSUE THREAD

**Issue by gulijiyag** [zfcampus/zf-apigility-doctrine#265]
Is there any tutorial, example or whatever that shows the usage of this module? I'm really lost with it, I don't know how to integrate and I can't find anything on the internet that could help me.
I though that this module was giving me a new tab on the admin ui or something like that, but it doesn't.

**Comment by TomHAnderson** [comment]
A good point.  I have been working on how to better document this and had some inspiration tonight.  Stay tuned this week.

**Comment by gulijiyag** [comment]
@TomHAnderson Thank you for the fast reply, you are amazing and keep up with the good work. I'm really looking forward for that documentation.

**Comment by gulijiyag** [comment]
@TomHAnderson I hope you don't forget about us this week, thank you in advance.

**Comment by TomHAnderson** [comment]
@gulijiyag This will be my answer to your need:  https://github.com/API-Skeletons/zf-doctrine-querybuilder

A Video Tutorial link for each library I'm in charge of.  zf-apigility-doctrine will be much harder than this first repository but since you requested here is your answer.

**Comment by gulijiyag** [comment]
This tutorial is for the querybuilder, what about this module (apigility doctrine)? @TomHAnderson

**Comment by TomHAnderson** [comment]
Yes.  I needed a platform to test the work and get experience.  I'll build one for zf-apigilty-doctrine in the coming week.

**Comment by gulijiyag** [comment]
@TomHAnderson is it going to be open - the tutorial, or paid?
