### ISSUE TITLE
Autodiscovering

### ISSUE THREAD

**Issue by karborator** [zfcampus/zf-apigility-doctrine#268]
I'm not able to use auto discovering with doctrine. Is it even possible ? 
If yes what is the guide I should follow ... configs etc ? 

"No entities found
Auto discovery could not find any existing entities, or those entities have already been exposed through Doctrine-connected services. "

**Comment by TomHAnderson** [comment]
You have the Admin installed and you are selecting the correct object manager?

**Comment by karborator** [comment]
Yes

**Comment by jguittard** [comment]
@karborator how does it go?

**Comment by webimpress** [comment]
Tested on latest version - `zf-apigility-skeleton 1.4.1` and `zf-apigility-doctrine 2.1.0`:
https://github.com/webimpress/zf3-apigility-doctrine
Autodiscovering form ORM database works as expected.

@karborator If you notice any further problems please reopen this issue with more informations. Thanks!
