### ISSUE TITLE
Entity Hal and Versioning Problems

### ISSUE THREAD

**Issue by wshafer** [zfcampus/zf-apigility-doctrine#273]
Hey Guys,

I'm having an issue as I attempt to lock down our API's version 1 and create a new version 2.  

The issue I'm running into is that zf-hal only allows one hydrator per instance, so when creating a doctrine connected resource adds a line like:

```
            'Db\\Entity\\User' => array(
                'route_identifier_name' => 'user_id',
                'entity_identifier_name' => 'id',
                'route_name' => 'myapi.rest.doctrine.user',
                'hydrator' => 'MyApi\\V1\\Rest\\User\\UserHydrator',
                'max_depth' => 2,
            ),
```

With our V2 we actually need different hydrators for these entities, for each version.  Currently with this setup, this doesn't appear possible.  Not without versioning my entities and creating another ORM to process these.

**Comment by TomHAnderson** [comment]
Per-resource hydrators were introduced here: https://github.com/zfcampus/zf-apigility-doctrine/releases/tag/2.0.1-beta

But the problem for you will remain that references from the hydrator will use the hydrator defined for the entity.

So a V2 Artist resource can specify it's own hydrator but when Artist->Album is referenced the hydrator for Album will come from the Album `zf-hal metadata_map` configuration.

**Comment by wshafer** [comment]
That's correct.  The problem is on the reference.  I'm not sure exactly how to fix this issue, short of versioning our enities.  But since the db config is on the entities, that doesn't seem to make sense either.

**Comment by TomHAnderson** [comment]
I think zf-hal should support versioning.  This isn't an issue for zf-apigility-doctrine at any rate and I don't see another culprit except zf-hal.  I suggest you open a ticket on that project.

**Comment by wshafer** [comment]
Ok.  I think I'm following what you're saying.  I'll open a ticket upstream.  Thanks for the help.

**Comment by manuelmeister** [comment]
@wshafer have you solved this problem?

@TomHAnderson why is this a problem of zf-hal?

**Comment by wshafer** [comment]
@manuelmeister  - Actually I ditched this module.  Instead I use Doctrine to manage and map the DB exactly.  I have separate Entities for v1/ v2/ etc and use a hydrator to populate these entities from the Doctrine Entity.

Since the DB doesn't always map 1 to 1 with the API responses, it made way more sense for me to break out the API and DB models and treat these as two distinct things.  While it caused me to write a bit more code, it actually simplified the api alot.  No more magical hydration and each version can map to the correct DB columns correctly.
