### ISSUE TITLE
property name `version` breaks api

### ISSUE THREAD

**Issue by jensstalder** [zfcampus/zf-apigility-doctrine#275]
It took me forever to figure out that naming a entity's property `version` completely destroys the implementation because the `findEntity` method of `ProjectResource` uses $routeParams to determine additional criterias. Because apigility sends the api version through routeParams apigility-doctrine automatically adds this property as a criteria :-( causing `No result was found for query although at least one row was expected.` errors.

https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Resource/DoctrineResource.php#L718

**Comment by TomHAnderson** [comment]
Sorry for your frustration.  Will you post an example route?  
Apigility promotes Media Type versioning: https://apigility.org/documentation/api-primer/versioning

So I'm suspicious that the version is a route parameter in a Media Type implementation.

**Comment by jensstalder** [comment]
Ja at least its an easy workaround by renaming the property.

I'm using a standard generated route:

```
     'api.rest.doctrine.project' => array(
                'type' => 'Segment',
                'options' => array(
                    'route' => '/project[/:project_id]',
                    'defaults' => array(
                        'controller' => 'api\\V1\\Rest\\Project\\Controller',
                    ),
                ),
            ),
```

Allowing for versioned media types of course :-)

```
    'accept-whitelist' => array(
            'api\\V1\\Rest\\Project\\Controller' => array(
                0 => 'application/vnd.api.v1+json',
                1 => 'application/hal+json',
                2 => 'application/json',
            ),
     ),
```

Beats me why they would need to inject `version` into the params.

**Comment by TomHAnderson** [comment]
Does this help?
https://github.com/zfcampus/zf-versioning/blob/master/src/VersionListener.php#L76

There's a preferred name of `zf_ver_version` there which is coming from the routeParams.  It may be where the route Params are assembled that is to blame.

**Comment by TomHAnderson** [comment]
I wonder if we change this https://github.com/zfcampus/zf-versioning/blob/master/src/PrototypeRouteListener.php#L34 to 'zf_ver_version' would it fix it?  

Is your app in a position to test this idea, @jensstalder ?

**Comment by jensstalder** [comment]
Oh ok? So setting a version parameter is still supported if no version is specified in Accept. Didn't know that. 
Does seam like if zf_ver_version takes precedence it should be defaulted instead of version. I'l give it a shot.

**Comment by jensstalder** [comment]
Nä, I changed it, but apparently its being set somewhere else.
Odd even explicitly setting Accept to `application/vnd.api.v1+json` still sets the version param anyways even though it should then be retrieved through zf_ver_version instead.

But thanks for the help, I will just rename the prop. Just wanted a heads-up for people that could run into this in the future.

**Comment by jensstalder** [comment]
Or one could simple extend over ProjectResource->findEntity and set the criterias explicitly.

**Comment by TomHAnderson** [comment]
I strongly recommend you don't add code to the extended resources, ever.  Anything you need to do should be handled outside the resource.

I think you've found a bug in the versioning of zfcampus.  If you don't want to track it down I'll take it and put in a patch.

**Comment by TomHAnderson** [comment]
@jensstalder try setting all 'version' to 'zf_ver_version' in https://github.com/zfcampus/zf-versioning/blob/master/src/PrototypeRouteListener.php

That carried through for me and worked on my single version API.

**Comment by jensstalder** [comment]
Yup!!! that acually works. I forgot to change `$this->versionRouteOptions['defaults']['version']` last time.
<img width="1130" alt="screen shot 2016-09-27 at 00 15 09" src="https://cloud.githubusercontent.com/assets/4964495/18853836/a4505d22-8447-11e6-8594-566ea0ff1570.png">

**Comment by webimpress** [comment]
@jensstalder @TomHAnderson Please see my solution in #303
