### ISSUE TITLE
Nice way to use apigility-doctrine HAL entity return in an RPC service

### ISSUE THREAD

**Issue by jensstalder** [zfcampus/zf-apigility-doctrine#279]
Is there a nice way of returning a HAL Doctrine Entity in an RPC Service?

**Comment by jguittard** [comment]
Sure thing!
I suggest you have a look [at the documentation](https://apigility.org/documentation/recipes/hal-from-rpc) ;)

**Comment by jguittard** [comment]
Closing issue, unless you have further questions.

**Comment by jensstalder** [comment]
Ja, but I can't get it to work with doctrine entities.

**Comment by jguittard** [comment]
Would you be able to detail a bit?
Maybe share a piece of code from your RPC controller?

**Comment by jensstalder** [comment]
```
use ZF\Hal\Entity as HalEntity;

uploadAction(){
        /* upload $path  */
        $media = new \Db\Entity\Media;
        $media->setPath($path);
        $this->em->persist($media);
        $this->em->flush();
        // return array(
        //     'id' => $media->getId(),
        //     'path' => $media->getPath()
        // );
        return array('payload' => new HalEntity($media, $media->getId()));
}
```

**Comment by jguittard** [comment]
`payload` has to be passed as a parameter of a `ZF\ContentNegotiation\ViewModel` instance, as detailed in the [documentation](https://apigility.org/documentation/recipes/hal-from-rpc) (second block of code)
```php
use ZF\Hal\Entity as HalEntity;
use ZF\ContentNegotiation\ViewModel;

public function uploadAction(){
        /* upload $path  */
        $media = new \Db\Entity\Media;
        $media->setPath($path);
        $this->em->persist($media);
        $this->em->flush();

        return new ViewModel([
            'payload' => new HalEntity($media, $media->getId())
        ]);
}
```

**Comment by jensstalder** [comment]
Sadly already tried that as well. :-(

**Comment by jguittard** [comment]
- What have you tried that is supposed to work (_your_ example would not)?
- What is the result of your code?

Please give as much information as possible, so that we can be helpful. Thank you.

**Comment by jensstalder** [comment]
It simply returns a empty {}

Should't there be a easy way to utilize ZF\Apigility\Doctrine\Server\Resource\DoctrineResource to hydrate the Object into HAL in an RPC?

**Comment by TomHAnderson** [comment]
@jensstalder set the content negotiation to haljson

```
    'zf-content-negotiation' => array(
        'controllers' => array(
            'ModuleName\\V1\\Rpc\\DoRpc\\Controller' => 'HalJson',
        ),
```

**Comment by jguittard** [comment]
`ZF\Apigility\Doctrine\Server\Resource\DoctrineResource` is not responsible for hydrating entities. `ZF\Hal` is. So what is your content-negotiation configuration?

**Comment by jensstalder** [comment]
Oh wow! Sorry ^^. that worked like a charm.

**Comment by jensstalder** [comment]
Sorry for the rookie mistake...

**Comment by jguittard** [comment]
@TomHAnderson thx for bringing it 10 seconds before me!
@jensstalder That's OK! Glad it worked out!

**Comment by jguittard** [comment]
@jensstalder [Documentation](https://apigility.org/documentation/recipes/hal-from-rpc) (again) at the very bottom! #RTFM :)
