### ISSUE TITLE
object_manager key in 'doctrine-connected' not saved

### ISSUE THREAD

**Issue by exptom** [zfcampus/zf-apigility-doctrine#284]
Using the latest stable versions (my composer.json):

```
"zfcampus/zf-apigility": "^1.4",
"zfcampus/zf-apigility-documentation": "^1.2",
"zfcampus/zf-apigility-doctrine": "^2.1",
"zfcampus/zf-doctrine-querybuilder": "^1.5"
```

Created a new API and then a single doctrine connected service. The generated service is very simple, it just allows GET on entity and collection.
Relevant portion of generated apigility config:

```
'zf-apigility' => [
        'doctrine-connected' => [
            \Api_Colouring\V1\Rest\ServiceType\ServiceTypeResource::class => [
                'object_manager' => null,       // THIS KEY IS BEING SET TO NULL
                'hydrator' => 'Api_Colouring\\V1\\Rest\\ServiceType\\ServiceTypeHydrator',
            ],
        ],
    ],
    'doctrine-hydrator' => [
        'Api_Colouring\\V1\\Rest\\ServiceType\\ServiceTypeHydrator' => [
            'entity_class' => \Colouring\Entity\ServiceType::class,
            'object_manager' => 'doctrine.entitymanager.orm_default',
            'by_value' => false,
            'strategies' => [],
            'use_generated_hydrator' => true,
        ],
    ],
```

Note that the `object_manager` key under the `doctrine_connected` config is set to `null`. This results in this error: `Fatal error: Call to a member function createQuery() on null in /vagrant/vendor/zfcampus/zf-apigility-doc`.

If I manually change the `null` to `'doctrine.entitymanager.orm_default'` then everything works as expected and the api returns the entity collection. 

Everytime I make a change in the apigility UI and save the `object_manager` key gets set back to null again.

**Comment by webimpress** [comment]
It was already reported in #278 and it's resolved in https://github.com/zfcampus/zf-apigility-admin-ui/pull/130. I will leave it open until fix is released.

**Comment by exptom** [comment]
Apologies for missing the existing ticket. Any ideas on a timescale for a bugfix release?

**Comment by exptom** [comment]
This is now merged and tagged inhttps://github.com/zfcampus/zf-apigility-admin-ui/pull/130 so the issue is resolved.
