### ISSUE TITLE
Question/Problem :: Add data with POST on a @ORM\OneToMany relation 

### ISSUE THREAD

**Issue by catadoctari** [zfcampus/zf-apigility-doctrine#285]
Hi,

So, I have two Entities:

```
class Contacts
{
   ...
    /**
     * @ORM\OneToMany(
     *     targetEntity="Contact\V1\Entity\PersonalData",
     *     mappedBy="contact",
     *     fetch="EAGER",
     *     cascade={"persist","remove"}
     * )
     */
    private $personalData;

   public function __construct()
    {
        $this->personalData = new \Doctrine\Common\Collections\ArrayCollection();
    }

   /**
     * Add personalData
     *
     * @param \Contact\V1\Entity\PersonalData $personalData
     *
     * @return Contacts
     */
    public function addPersonalData(\Contact\V1\Entity\PersonalData $personalData)
    {
        $this->personalData[] = $personalData;

        return $this;
    }

    /**
     * Remove personalData
     *
     * @param \Contact\V1\Entity\PersonalData $personalData
     */
    public function removePersonalData(\Contact\V1\Entity\PersonalData $personalData)
    {
        $this->personalData->removeElement($personalData);
    }

    /**
     * Get personalData
     *
     * @return \Doctrine\Common\Collections\Collection
     */
    public function getPersonalData()
    {
        return $this->personalData;
    }
    ...
}
class PersonalData
{
    /**
     * @ORM\ManyToOne(
     *     targetEntity="Contact\V1\Entity\Contacts",
     *     inversedBy="personalData",
     *     fetch="EAGER",
     *     cascade={"persist","remove"}
     * )
     * @ORM\JoinColumn(name="contacts_id", referencedColumnName="id", nullable=false)
     */
    private $contact;

    /**
     * Set contact
     *
     * @param \Contact\V1\Entity\Contacts $contact
     *
     * @return PersonalData
     */
    public function setContact(\Contact\V1\Entity\Contacts $contact)
    {
        $this->contact = $contact;

        return $this;
    }

    /**
     * Get contact
     *
     * @return \Contact\V1\Entity\Contacts
     */
    public function getContact()
    {
        return $this->contact;
    }
    ...
}

// p.s.Geters and setter are generated with  ./vendor/doctrine/doctrine-module/bin/doctrine-module orm:generate-entities ./module/Contact/src/ --generate-annotations=true

```

And now I want to create a Contact with a simple POST request on http://myapp/contacts with the following JSON:

`{
  "personalData": [{
                    "value": "+505050",
                    "note": "only 12-13",
                    "active": true,
                    "type": {
                        "id": "2"
                    }
     }]
}`

The problem is that the _public function addPersonalData(\Contact\V1\Entity\PersonalData $personalData)_ receives as parameter a _\Doctrine\Common\Collections\ArrayCollection_ and not a _\Contact\V1\Entity\PersonalData_. and of course and _"status":500,"detail":"An error occurred during execution; please try again later."_ occurs. 

I am using hydrate byValue, and the _DoctrineModule\Stdlib\Hydrator\Strategy\AllowRemoveByValue hydrate()_ function on line 70 it really seams to _$toAdd    = new ArrayCollection(array_udiff($value, $collection, array($this, 'compareObjects')));_ create an ArrayCollection.

Some help will be welcome.
Thank you,
Best

**Comment by TomHAnderson** [comment]
Use the `personalData` endpoint to create a `personalData` entity.  Include the primary key of the contact to assign it to.

```
POST /personalData
{
    "contact": 1
}
```

**Comment by jguittard** [comment]
```php
public function addPersonalDatas(\Doctrine\Common\Collections\Collection $personalDatas)
{
    /** @var \Contact\V1\Entity\PersonalData */
    foreach($personalDatas as $personalData) {
        $this->personalData->add($personalData);
    }
}
```
Same goes with `removePersonalDatas`

**Comment by catadoctari** [comment]
Thx @jguittard 

I only added an extra line _$personalData->setContact($this);_ and it work fine. 

`public function addPersonalData(\Doctrine\Common\Collections\Collection $personalDatas)
    {
        /** @var $personalData \Contact\V1\Entity\PersonalData */
        foreach($personalDatas as $personalData) {
            $personalData->setContact($this);
            $this->personalData->add($personalData);
        }

        return $this;
    }`
