### ISSUE TITLE
naming strategy ?

### ISSUE THREAD

**Issue by karborator** [zfcampus/zf-apigility-doctrine#286]
I'm trying to change the naming_strategy of entity properties from camelCase -> under_score , 
so what i'm doing to achieve the goal is to setup an configuration like: 

```
'doctrine' => [
        'configuration' => [
            'orm_default' => [
                'naming_strategy' => \Doctrine\ORM\Mapping\UnderscoreNamingStrategy::class
            ],
        ],
```

plus a factory for this UnderscoreNamingStrategy . 

Then I just execute

`php ./vendor/doctrine/doctrine-module/bin/doctrine-module orm:convert-mapping --namespace="Application\\Entity\\" --force --from-database annotation ./module/Application/src/Entity/`

but the class properties are still in camelCase .. 

Any suggestions ?

**Comment by gsomoza** [comment]
Looks like your issue is related to doctrine/DoctrineModule rather than this repository, and they already have an issue going on that may be similar to what you're experiencing: https://github.com/doctrine/DoctrineModule/issues/554

**Comment by webimpress** [comment]
@karborator As @gsomoza suggested, this is not right repository for this issue, please see related issue. Thanks!
