### ISSUE TITLE
Cannot attach listeners via config

### ISSUE THREAD

**Issue by rradutzu** [zfcampus/zf-apigility-doctrine#287]
I am trying to attach listeners to my REST resources using the config 
(zf-apigility.doctrine-connected.resource_name.listeners), but they don't get triggered.

I tried to debug the problem and got the following observations:

In the file: zfcampus/zf-apigility-doctrine/src/Server/Resource/DoctrineResource.php line 148.
the method getEventManager is called which is returning a new instance of the event manager if one is not set:

`$this->setEventManager(new EventManager());`

This is instantiating a new Event Manager without specifying the Shared Event Manager for it.

Example:
`$this->setEventManager(new EventManager($this->getSharedEventManager()));`

This is causing the code in: /projects/carrier-rules-engine-apigility-upgrade/vendor/zendframework/zend-mvc/src/Service/ServiceManagerConfig.php line 99 to return a brand new event manager, and loosing all attached events:

`// If the instance has an EM WITH an SEM composed, do nothing.`
`if ($eventManager instanceof EventManagerInterface`
`   && $eventManager->getSharedManager() instanceof SharedEventManagerInterface`
` ) {`
       `   return;`
` }`
`$instance->setEventManager($container->get('EventManager'));`

**Comment by webimpress** [comment]
@rradutzu Thanks for reporting this issue.
I was testing it and your solution seems to be correct for me.
Would you like submit PR with your solution and add some tests for it?
