### ISSUE TITLE
Change Entitymanager for DoctrineResource

### ISSUE THREAD

**Issue by Iraecio** [zfcampus/zf-apigility-doctrine#292]
Hello
I'm having a hard time changing the entitymanager to be used by DoctrineResoucer.
I'm trying to switch through a factory to the Resource but until now there was an error

someone know how i can change Entity manager befores create,fetch...

**Comment by TomHAnderson** [comment]
It's in the configuration:

```
    'zf-apigility' => array(
        'doctrine-connected' => array(
            'NVPApi\\V1\\Rest\\Project\\ProjectResource' => array(
                'object_manager' => 'doctrine.entitymanager.orm_default',
```

**Comment by Iraecio** [comment]
Yes, but whenever I change the orm it has already loaded the orm_default,
For example when a user makes the request, I detect the data of the request and change according to the order of it, but always comes the default;

**Comment by TomHAnderson** [comment]
If you need to use different object managers then use different REST controllers.  Hot swapping object managers is not the intention.

**Comment by karborator** [comment]
How we can implement 
http://symfony.com/doc/current/doctrine/multiple_entity_managers.html
?
