### ISSUE TITLE
Query Create Filter on patch/update too?

### ISSUE THREAD

**Issue by kusmierz** [zfcampus/zf-apigility-doctrine#294]
Shouldn't `$this->getQueryCreateFilter()->filter` be called in patch/update methods too?

Now we have a little bit curious situation, when we have filtered input on create, but few seconds later we could update the entity with no limits...

**Comment by TomHAnderson** [comment]
patch and update are not creating.  For those a Query Provider is used.

**Comment by kusmierz** [comment]
I know, but let's imagine, I've created QueryCreateFilter which filters provided fields and leaves only some of them, i.e.: I've got `name` and `id` fields from API, but after QueryCreateFilter::filter, only `name` left. But then, I `patch` my new entity with another `name` and `id`, but now there is no filter at all, so my `id` field would change, but I don't want to...

**Comment by TomHAnderson** [comment]
I'll need you to show code to help more than this:  id should not be a field which is approved for that entity through the fields section of the Apigility UI.

**Comment by kusmierz** [comment]
`id` field was just an example, maybe not best one. The main problem is I've roles (scopes in fact) - one user could create and update field "`A`", but second one should not. `QueryCreateFilter::filter` was perfect to filter those fields (as I have `identity` there), but I can't do the same for updates/patches...

**Comment by TomHAnderson** [comment]
Are you using api-skeletons/zf-oauth2-doctrine?   How about api-skeletons/zf-oauth2-doctrine-identity?

You do have access to $identity from within a query provider.

**Comment by kusmierz** [comment]
Yes, I'm using both. I have access to `$identity` in Query Provider as well.

But I believe I can't change `$data` there.

in example:

```php
<?php
        $this->dispatch(
            sprintf('/somthing/1'),
            'PATCH',
            [
                'name' => 'New Name',
                'is_public' => 'Field which only some users could change',
            ]
        );
```

OK, then in `\ZF\Apigility\Doctrine\Server\Resource\DoctrineResource::patch`, I have `$this->findEntity` first, which calls my query provider, but I can't see the way to change `$data`, which later is passed to `hydrate` method. In other word, I can't remove `is_public` field to deny changing it (ok, I could return `ApiProblem`, but I prefer silently fail).

**Comment by TomHAnderson** [comment]
Is $data an ArrayObject?

**Comment by kusmierz** [comment]
`\ZF\Apigility\Doctrine\Server\Query\Provider\QueryProviderInterface`'s phpdoc says `$data` is an array. I could do this using ArrayObject, but I thought there is better way to filter this (changing data in `createQuery` method doesn't look too good anyway).

**Comment by TomHAnderson** [comment]
You didn't answer my question.  I'm asking you to run get_class on $data inside your code.

**Comment by kusmierz** [comment]
ah, sorry, I thought it's statement. `$data` is simple array there.

**Comment by TomHAnderson** [comment]
Two things here:

1. I think ArrayObject should be used for all resource in Apigility.  That's a large change.

2. If your user is posting a field which they shouldn't then the correct course of action is to throw an ApiProblem.

**Comment by kusmierz** [comment]
About 1st... Probably. But then I need to cast it manually in each and every of my resource's methods (ie. `return parent::patch($id, new ArrayObject($data));`, right?). But definitely would be easier then.

And if I agree with your 2nd point, where do you think it is right place to check (validate) it? Query Provider's `createQuery` method again?

**Comment by TomHAnderson** [comment]
Yes, data validation is in the Query Provider or Query Create Filter

**Comment by TomHAnderson** [comment]
See http://book.apiskeletons.com/en/latest/security.html#query-providers

ok to close this.
