### ISSUE TITLE
listeners, query_create_filter and query_providers keys in 'doctrine-connected' not saved

### ISSUE THREAD

**Issue by kusmierz** [zfcampus/zf-apigility-doctrine#295]
At least these 3 keys are removed after REST service save.

```php
'zf-apigility' => [
        'doctrine-connected' => [
            \Api\V1\Rest\Something\SomethingResource::class => [
                'object_manager' => 'doctrine.entitymanager.orm_default',
                'hydrator' => 'Api\\V1\\Rest\\Something\\SomethingHydrator',
                'listeners' => [],
                'query_create_filter' => \Api\V1\Rest\Something\SomethingCreateFilter::class,
                'query_providers' => [
                    'default' => \Api\V1\Rest\Something\SomethingQueryProvider::class,
                ],
            ],
```

and after saving (with no single change in UI):

```php
'zf-apigility' => [
        'doctrine-connected' => [
            \Api\V1\Rest\Something\SomethingResource::class => [
                'object_manager' => 'doctrine.entitymanager.orm_default',
                'hydrator' => 'Api\\V1\\Rest\\Something\\SomethingHydrator',
            ],
```

**Comment by TomHAnderson** [comment]
This is certainly an issue.  My research is pointing towards 
https://github.com/zfcampus/zf-configuration/blob/master/src/ConfigResource.php#L118

The ConfigResouce patchKey uses replaceKey to do the work without merging the existing config passed to replaceKey.

**Comment by TomHAnderson** [comment]
The PR listed above fixes this problem.

**Comment by kusmierz** [comment]
I patched only `src/Admin/Model/DoctrineRestServiceModel.php` (onto 2.1.0), tried "Save" (without any changes in UI) one more time and... Hm, those keys referred above stays 🎉, but unfortunately I have other issues then.

For some reason, it added me all http keywords in 'entity_http_methods' key, so it changes

```php
'zf-rest' => [
        'Api\\V1\\Rest\\Something\\Controller' => [
            'listener' => \Api\V1\Rest\Something\SomethingResource::class,
            'route_name' => 'api.rest.something',
            'route_identifier_name' => 'something_id',
            'collection_name' => 'something',
            'entity_http_methods' => [
                0 => 'GET',
                2 => 'PATCH',
                3 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
            ],
            'collection_query_whitelist' => [],
            'page_size' => '25',
            'page_size_param' => null,
            'entity_class' => \Api\V1\Rest\Something\SomethingEntity::class,
            'collection_class' => \Api\V1\Rest\Something\SomethingCollection::class,
            'service_name' => 'Something',
            'entity_identifier_name' => 'id',
        ],
],
```

into 


```php
'zf-rest' => [
        'Api\\V1\\Rest\\Something\\Controller' => [
// ...
            'entity_http_methods' => [
                0 => 'GET',
                2 => 'PATCH',
                3 => 'DELETE',
                4 => 'GET',
                5 => 'PATCH',
                6 => 'DELETE',
            ],
            'collection_http_methods' => [
                0 => 'GET',
                1 => 'POST',
                2 => 'GET',
                3 => 'POST',
            ],
// ...
        ],
],
```

And added those two keys into "global" namespace config array:

```php
[
    'zf-rest' => [ ... ],
    'doctrine' => [ ... ],
    // ...
    'object_manager' => 'doctrine.entitymanager.orm_default',
    'hydrator' => 'Api\\V1\\Rest\\Something\\SomethingHydrator',
]
```

I've reverted changes (my config, and `DoctrineRestServiceModel.php` as well) and tried "Save" configuration again... and it "just" removed those 3 keys (listeners, query_create_filter and query_providers).

**Comment by TomHAnderson** [comment]
I replaced every patchKey with patch, but patchKey implements a PUT not a PATCH.  So your example of a zf-rest configuration should be implemented with PUT, but `zf-configuration` does not support a PUT method as replace and only implements `replaceKey`.

I'll look again, and more closely, at the `patch()` calls and likely revert at least `zf-rest` patches.

**Comment by TomHAnderson** [comment]
I reverted every numeric array indexed config back to updateKey (PUT).  I think this will solve your problem and I know of no custom keys inside these config sections.

**Comment by kusmierz** [comment]
Thanks @TomHAnderson! Works almost perfect. But still have two more config keys added:

```php
[
    'zf-rest' => [ ... ],
    'doctrine' => [ ... ],
    // ...
    'object_manager' => 'doctrine.entitymanager.orm_default',
    'hydrator' => 'Api\\V1\\Rest\\Something\\SomethingHydrator',
]
```

See my comment in #296.

**Comment by TomHAnderson** [comment]
That certainly was wrong.   I've fixed it per your suggestion.  Please try again.  If you green light it I'll push it to get patched.

**Comment by kusmierz** [comment]
Great, at least for my case works perfect! Thank you one more time :)
