### ISSUE TITLE
ZF\Apigility\Admin dependency missing

### ISSUE THREAD

**Issue by inbaz** [zfcampus/zf-apigility-doctrine#300]
When installing zf-apigility-doctrine it says:

Module "ZF\Apigility\Doctrine\Admin" depends on module "ZF\Apigility\Admin", which was not initialized before it

Shouldn't there be a require statement for this missing module inside of this one?

**Comment by TomHAnderson** [comment]
https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Admin/Module.php#L28

What more do you think is needed?  If you're referring to composer.json require it's not because this can be installed without the admin and should be installed that way for a deployment.

**Comment by inbaz** [comment]
https://github.com/zfcampus/zf-apigility-doctrine/blob/master/composer.json#L34

zf-apigility is already a requirement within the composer.json. I wondered why zf-apigility-admin isn't required automatically as well. Is it for the reason that there is a admin and a server part and the server part does not need the zf-apigility-admin?

**Comment by TomHAnderson** [comment]
My previous answer is still correct.

**Comment by webimpress** [comment]
@inbaz in prod env you don't need zf-apigility-admin, this is why it's not required in composer and I think this is what @TomHAnderson said :)

For me all seems to be fine.
