### ISSUE TITLE
How to add dependency inside resource?

### ISSUE THREAD

**Issue by brndusic** [zfcampus/zf-apigility-doctrine#302]
How can we add a dependency to a resource? Can someone explain how can we use a custom service inside a resource because we do not have access to ServiceManager anymore.

What I want to accomplish is for example to totally override one method inside a resource as others remain untouched.

**Comment by snapshotpl** [comment]
Use constructor injection

**Comment by TomHAnderson** [comment]
I strongly recommend you do not modify the resources.  You probably just need a query provider instead.

**Comment by TomHAnderson** [comment]
@brndusic For every method in DoctrineResource there is an event you can subscribe to which will allow you to stop the method and return your result.  This is a little hackish but it solves your problem cleanly.

https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Resource/DoctrineResource.php#L574

**Comment by webimpress** [comment]
@brndusic Did you resolve your issue? You've got two good suggestions, please reopen the issue if you have any further questions.
