### ISSUE TITLE
Validator factory not work

### ISSUE THREAD

**Issue by fabioginzel** [zfcampus/zf-apigility-doctrine#306]
In server.conf.php the factory of NoObjectExists and ObjectExists not work

**Comment by TomHAnderson** [comment]
Those each work fine for me.  Can you provide more detail?

**Comment by fabioginzel** [comment]
@TomHAnderson see my commit plz

**Comment by TomHAnderson** [comment]
I do not see an issue with the zf-apigility-doctrine factory: https://github.com/zfcampus/zf-apigility-doctrine/blob/master/src/Server/Validator/ObjectExistsFactory.php#L59

Your fix overrides the validator for DoctrineModule though those classes are used in these validator factories.

I do see that the validator factory may not be useful in a non-doctrine.entitymanager.orm_default ORM.  Please give more details.

**Comment by fabioginzel** [comment]
As you can see in the server.conf.php file, the reference to the Validator \ NoObjectExists and Validator \ ObjectExists class do not exist, which causes it to use invokablefactory instead of the correct factory

**Comment by TomHAnderson** [comment]
`ZF\Apigility\Doctrine\Validator\[No]ObjectExists` is configured in the `factories` section of the validators service manager array.  So trying to instantiate this class the service manager uses the factory which correctly creates the class.  I see no issue with the configuration as-is.

**Comment by fabioginzel** [comment]
The problem is that the factories session configures the factory for "ZF\Apigility\Doctrine\ServerValidator\[No]ObjectExists::class", but that class does not exists. My commit solves this issue.

The only reason that the validators are being built is duo to the Invokable Factory that happens to build then right. But when I try to use another abstract factory as a default for my application, it crashes.

**Comment by TomHAnderson** [comment]
> "ZF\Apigility\Doctrine\Server\Validator[No]ObjectExists::class", but that class does not exists.

Yes, that is intentional.  I think your problem lies somewhere else.

**Comment by fabioginzel** [comment]
If i put 
`    'validators' => [
        'abstract_factories' => [
            ConfigAbstractFactory::class,
            ReflectionBasedAbstractFactory::class,
        ],
`
in my config file, [No]ObjectExists no longer works

**Comment by TomHAnderson** [comment]
Do one of those factories not correctly report the list of aliases they create?  
```
interface AbstractFactoryInterface extends FactoryInterface
{
    /**
     * Does the factory have a way to create an instance for the service?
     *
     * @param  ContainerInterface $container
     * @param  string $requestedName
     * @return bool
     */
    public function canCreate(ContainerInterface $container, $requestedName);
}
```

If your abstract factory is reporting that it can create anything under the sun that would be a problem.

**Comment by webimpress** [comment]
@fabioginzel 

I've tried it with zf-apigility-admin and field is created with validator `ZF\\Apigility\\Doctrine\\Server\\Validator\\NoObjectExists`.

Here is part of my generated configuration (`module.config.php`):

```php
    'input_filter_specs' => [
        'NewApi\\V1\\Rest\\Album\\Validator' => [
            0 => [
                'name' => 'name',
                'required' => false,
                'filters' => [],
                'validators' => [
                    0 => [
                        'name' => 'ZF\\Apigility\\Doctrine\\Server\\Validator\\NoObjectExists',
                        'options' => [
                            'entity_class' => \Application\Entity\Album::class,
                            'fields' => 'name',
                        ],
                    ],
                ],
            ],
...
```

All seems to be fine.

**Comment by fabioginzel** [comment]
@webimpress  but if i dont use zf-apigility-admin, this not work

**Comment by webimpress** [comment]
@fabioginzel How do you mean? You don't need to use `zf-apigility-admin`.

Are you using then `ZF\Apigility\Doctrine\Server\Validator\NoObjectExists` / `ZF\Apigility\Doctrine\Server\Validator\ObjectExists` validators or you try to use `DoctrineModule\Validator\NoObjectExists` / `DoctrineModule\Validator\ObjectExists` straight away?

If you want use names from `DoctrineModule` you __have to__ provide factories for them. This library provides __different aliases__ consistent with the library with factories which produces configured validators. Yes, these are instances of validators from `DoctrineModule`.

**Comment by fabioginzel** [comment]
where are ZF\Apigility\Doctrine\Server\Validator\NoObjectExists /  and ZF\Apigility\Doctrine\Server\Validator\ObjectExists ??

**Comment by webimpress** [comment]
@fabioginzel These are __virtual services__ defined here:
https://github.com/zfcampus/zf-apigility-doctrine/blob/master/config/server.config.php#L52-L53

If you want to use these validators from that package you should use these virtual services.
