### ISSUE TITLE
Include link to book in README

### ISSUE THREAD

**Issue by TomHAnderson** [zfcampus/zf-apigility-doctrine#321]
After working on a couple projects from users to took this library and tried to use it it was apparent that a _design_ was necessary.

I created a working design and documented it throughly here: http://book.apiskeletons.com/en/latest/
Start with the Cliff notes: http://book.apiskeletons.com/en/latest/summary.html

I am petitioning that this documentation be referenced in the README of this library.

**Comment by webimpress** [comment]
Please see: 
https://github.com/zfcampus/zf-apigility-doctrine/pull/322#issuecomment-458178001
