### ISSUE TITLE
GET response doesn't show unidirectional ManyToOnes

### ISSUE THREAD

**Issue by tad3j** [zfcampus/zf-apigility-doctrine#34]
I've finally got ApigilityDoctrine working but I've noticed that when I make a get request OneToMany column looks like this:

    "app": {
        "__initializer__": {},
        "__cloner__": {},
        "__isInitialized__": false
    },

Any idea why?

**Comment by santiph** [comment]
@tad3j Kind of outdated, but I had the same issue today and I wanted to share my experience fixing it.

I could fix it only by creating a new service Doctrine-connected for the odd entity ("app" entity in your case). After that, new requests worked like a charm and I got the entity back as part of the _embedded object.

**Comment by smknstd** [comment]
@santiph thank you , your message helped !
