### ISSUE TITLE
Different Hydration depending on Request type

### ISSUE THREAD

**Issue by intellix** [zfcampus/zf-apigility-doctrine#84]
I've got relationships like:

Account hasMany Things

When I log the user in, I make a request for his Account and would like his things in one call so I have to have a config like:

```php
return array(
    'doctrine-hydrator' => array(
        'MyApp\\V1\\Entity\\AccountHydrator' => array(
            'entity_class' => 'MyApp\\V1\\Entity\\Account',
            'object_manager' => 'doctrine.entitymanager.orm_default',
            'by_value' => true,
            'use_generated_hydrator' => true,
            'strategies' => array(
                'monsters' => 'CollectionExtract'
            ),
        ),
        'MyApp\\V1\\Entity\\ThingHydrator' => array(
            'entity_class' => 'MyApp\\V1\\Entity\\Thing',
            'object_manager' => 'doctrine.entitymanager.orm_default',
            'by_value' => true,
            'use_generated_hydrator' => true,
            // Has to be CollectionLink or else we get nested exception
            'strategies' => array(
                'account' => 'CollectionLink'
            ),
        ),
    ),
);
```

And get the following response from a fetchAll: `GET /accounts/me`
```json
{
    "id": 1,
    "name": "Joe Bloggs",
    "things": [
        {
            "id": 1,
            "name": "Book",
            "account": null
        },
        {
            "id": 2,
            "name": "Pencil",
            "account": null
        }
    ]
}
```

All good.... but when I try to create a "Thing" with the following call: `POST /things`
```json
{
    "name": "Clock",
    "account": {
        "id": 1
    }
}
```

The account is never hydrated because of the CollectionLink on ThingHydrator. If I remove that, I get a nested exception.
I can get around this by removing all of the strategies and making individual calls but it seems eventually I'll end up removing all of my strategies and using the `zoom` functionality.
Is there a way around this or perhaps a way for me to specify hydrators depending on the call type? I think `POST/Create` shouldn't cause a nested exception.

**Comment by TomHAnderson** [comment]
intellix: anything to add or contribute on this topic?  I'll close the issue soon.

**Comment by intellix** [comment]
I suppose there isn't anything for me to add or contribute. Will close!
