### ISSUE TITLE
Doctrine OAuth2 Adapter

### ISSUE THREAD

**Issue by intellix** [zfcampus/zf-apigility-doctrine#88]
I think it would be good to have a Doctrine OAuth2 Adapter. Currently you almost always have to override both the Factory and Adapter in case you have more fields than `username`, `password`, `first_name` and `last_name`.
With a Doctrine OAuth2 adapter it means you can just specify your object manager and entities to retrieve whatever you want.

Just creating an issue to contain my PRs that will hopefully follow tonight.

**Comment by TomHAnderson** [comment]
I'm sure this will be built in time and I can see doing it myself when the need presses but although this module touches apigility and doctrine this request belongs in https://github.com/zfcampus/zf-oauth2
