### ISSUE TITLE
Show only entity properties that are defined as field in Apigility

### ISSUE THREAD

**Issue by pietervogelaar** [zfcampus/zf-apigility-doctrine#95]
By default all the properties of entities are exposed in the API. Is it an idea to show only properties that are defined as field of the REST service as soon as ONE field is added?

Like to hear your thoughts about this!

**Comment by gabrielsomoza** [comment]
You can use the Custom Filters feature I contributed to zf-doctrine-hydration-module https://github.com/phpro/zf-doctrine-hydration-module#custom-filters 

Its very similar to what @intellix proposed:

```php
'Thingy\\V1\\Entity\\UserHydrator' => array(
    'entity_class' => 'Thingy\\V1\\Entity\\User',
    'object_manager' => 'doctrine.entitymanager.orm_default',
    'by_value' => true,
    'use_generated_hydrator' => true,
    'strategies' => array(
        'password' => 'Password',
    ),
    'filters' => array(
        'custom.filter.name' => array(
            'condition' => 'and', //optional, default: FilterComposite::CONDITION_OR,
            'filter' => 'user.filter', // a name in the Service Manager
        ),
    ),
),
```

And then the class instantiated by 'user.filter' should implement `Zend\Stdlib\Hydrator\Filter\FilterInterface` to determine which properties will be allowed through and which not.

**Comment by Socengel** [comment]
@intellix @gabrielsomoza 
i think best practice is to use "DoctrineModule\Stdlib\Hydrator\Filter\PropertyName;" and factory for this filter.

> Module.php

```php
use DoctrineModule\Stdlib\Hydrator\Filter\PropertyName;

public function getServiceConfig()
{
	$user = [
		'password',
		'is_blocked',
		'client',
		'accessToken',
		'authorizationCode',
		'refreshToken'
	];
	return [
		'factories' => [
			'user_entity_filter' => function () use($user) {
				return new PropertyName($user, true);
			}
		]
	];
}
```

In this example i pass an array variable throughout anonimus function, but you can simply put array into constructor. As a candy second parameter of filter constructor determinates what to do with fields listed in array. They must be excluded (true) or only them must be showed (false).

And at the end of it all we need to configure hydrator in config to use this filter.

> module.config.php

```php
'doctrine-hydrator' => array(
    'User\\V1\\Rest\\User\\UserHydrator' => array(
        'entity_class' => 'DB\\User\\Entity\\User',
        'object_manager' => 'doctrine.entitymanager.orm_default',
        'by_value' => false,
        'strategies' => array(),
        'filters' => array(
            'password' => array(
                'condition' => 'and',
                'filter' => 'user_entity_filter',
            ),
        ),
        'use_generated_hydrator' => true,
    ),
),
```

i think this info must be in documentation ;).

**Comment by gabrielsomoza** [comment]
@Socengel I agree this is a good candidate to document but right now there doesn't seem to be anything further than the `README.md` in the homepage. I'd suggest you could submit a PR with this info inside a new file in the `./docs` folder - it should at least help get the ball rolling regarding better docs. What do you think?
